<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsSolid::class);

$title = "Hyvä Theme";
$content = "Where good stores begin.";
$link = "https://hyva.io/";
$cta = "Visit hyva.io";
?>
<div class="py-16 px-8 sm:py-24 lg:py-32 lg:px-16 rounded-2xl bg-linear-45 from-primary/20 via-secondary/20 to-primary/40">
    <hgroup class="mb-4 text-2xl sm:text-3xl text-primary-darker space-y-2">
        <h1 class="text-4xl sm:text-5xl font-bold"><?= $escaper->escapeHtml($title) ?></h1>
        <?php if ($content): ?>
            <p class="uppercase"><?= $escaper->escapeHtml($content) ?></p>
        <?php endif; ?>
    </hgroup>
    <p>
        <a class="btn btn-primary gap-4" href="<?= $escaper->escapeUrl($link) ?>">
            <?= $escaper->escapeHtml($cta) ?>
            <?= $heroicons->chevronDoubleRightHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
        </a>
    </p>
</div>

