<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
$uniqueId = '_' . uniqid();
$query = $block->getGraphqlQuery();
/**
 * Can be a custom filter, like  "color: { in: [\"yellow\",\"orange\"] },"
 * @var string $productFilters
 */
$productFilters = $block->getProductFilters();
$productSkus = $block->getProductSkus();
$categoryIds = $block->getCategoryIds();
$priceFrom = $block->getPriceFrom();
$priceTo = $block->getPriceTo();
$pageSize = $block->getPageSize() ?: '8';
$sortAttribute = $block->getSortAttribute() ?: 'position';
$sortDirection = $block->getSortDirection() ?: 'ASC';

$productSkuFilter = $productSkus ? sprintf("sku: { in: [\"%s\"] },", join("\",\"", explode(',',$productSkus))) : "";
$categoryFilter = $categoryIds ? sprintf("category_id: { in: [\"%s\"] }", join("\",\"", explode(',',$categoryIds))) : "";
$priceFilter = $priceFrom || $priceTo ? "price: { from: \"$priceFrom\", to: \"$priceTo\" }," : "";

$productAttributes = "
      sku
      id
      name
      small_image {
        label
        url
      }
      url_key
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
          final_price {
            value
            currency
          }
        }
      }";

$graphqlQuery = $query ?: "
{
  products(
    filter: {
      $productFilters
      $productSkuFilter
      $categoryFilter
      $priceFilter
      }
    pageSize: {$pageSize},
    sort: {{$sortAttribute}: {$sortDirection}}
    ) {
    items {
        $productAttributes
    }
  }
}";
?>
<script>
    function initSliderComponent<?= $uniqueId ?>() {
        return {
            products: [],
            get minHeight () {
                return this.products && '443px';
            },
            query: `<?= $graphqlQuery ?>`,
            getProducts($nextTick, $dispatch) {

                let response = fetch('<?= $block->getBaseUrl() ?>graphql?query=' + encodeURIComponent(
                    this.query
                ), {
                    method: 'GET',
                    headers: {'Content-Type': 'application/json'},
                }).then(response => response.json())
                    .then(
                        data => {
                            this.products = (data && data.data && data.data.products && data.data.products.items) || [];
                            $nextTick(function () {
                                window.loadLorySliders($dispatch);
                            });
                        }
                    );
            }
        }
    }

</script>
<section class="text-gray-700 body-font my-12"
    x-data="initSliderComponent<?= $uniqueId?>()"
    x-init="getProducts($nextTick, $dispatch); $nextTick(function() { window.loadLorySliders($dispatch); });"
    :style="`min-height: ${minHeight}`"
>
    <template x-if="products && products.length">
        <div class="js_slider relative container">
            <div class="js_frame w-full relative overflow-x-hidden">
                <div class="js_slides w-full relative flex flex-no-wrap" style="transition-timing-function: ease; transition-duration: 300ms; transform: translateX(0px);">
                    <template x-for="product in products">
                        <div class="js_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none">
                            <div class="p-2 mr-2 rounded-md bg-gray-100 hover:bg-gray-200">
                                <a :href="'<?= $block->getBaseUrl() ?>' + product.url_key + '.html'"
                                   class="relative product photo product-item-photo flex items-center bg-white"
                                   style="padding-top:100%"
                                   tabindex="-1">
                                    <span class="absolute h-full w-full align-center top-0 left-0 flex content-center flex-wrap p-2 overflow-hidden">
                                        <img class="w-full h-auto"
                                         :src="product.small_image.url"
                                         :alt="product.small_image.label"
                                         loading="lazy"
                                         width="500"
                                         height="500"
                                    />
                                    </span>
                                </a>

                                <p class="pt-3 flex items-center justify-center text-primary px-1">
                                    <a class="product-item-link truncate"
                                        :href="'<?= $block->getBaseUrl() ?>' + product.url_key + '.html'"
                                       >
                                        <span x-text="product.name"></span>
                                    </a>

                                </p>
                                <p class="pt-1 text-gray-900" x-text="new Intl.NumberFormat(document.documentElement.lang, { style: 'currency', currency: product.price_range.minimum_price.final_price.currency }).format(product.price_range.minimum_price.final_price.value)"></p>
                                <p class="p-3 flex flex-wrap inline">
                                    <a class="w-auto mr-auto btn btn-primary justify-center"
                                       :href="'<?= $block->getBaseUrl() ?>' + product.url_key + '.html'">
                                        <svg class="h-6 w-6 border-current" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
                                        </svg>
                                        Add to cart
                                    </a>
                                    <a class="w-auto ml-auto btn btn-secondary">
                                        <svg class="h-6 w-6 fill-current text-gray-500 hover:text-black" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                            <path d="M12,4.595c-1.104-1.006-2.512-1.558-3.996-1.558c-1.578,0-3.072,0.623-4.213,1.758c-2.353,2.363-2.352,6.059,0.002,8.412 l7.332,7.332c0.17,0.299,0.498,0.492,0.875,0.492c0.322,0,0.609-0.163,0.792-0.409l7.415-7.415 c2.354-2.354,2.354-6.049-0.002-8.416c-1.137-1.131-2.631-1.754-4.209-1.754C14.513,3.037,13.104,3.589,12,4.595z M18.791,6.205 c1.563,1.571,1.564,4.025,0.002,5.588L12,18.586l-6.793-6.793C3.645,10.23,3.646,7.776,5.205,6.209 c0.76-0.756,1.754-1.172,2.799-1.172s2.035,0.416,2.789,1.17l0.5,0.5c0.391,0.391,1.023,0.391,1.414,0l0.5-0.5 C14.719,4.698,17.281,4.702,18.791,6.205z"></path>
                                        </svg>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </template>
                </div>
            </div>
            <template x-if="products.length">
            <span class="js_prev prev bg-white bg-opacity-75 hover:bg-opacity-100 disabled absolute left-0 cursor-pointer"
                style="top: 50%; margin-top: -25px;"
                  x-show="products.length">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="50" viewBox="0 0 501.5 501.5"><g><path fill="#2E435A" d="M302.67 90.877l55.77 55.508L254.575 250.75 358.44 355.116l-55.77 55.506L143.56 250.75z"></path></g></svg>
            </span>
            <span class="js_next next bg-white bg-opacity-75 hover:bg-opacity-100 absolute right-0 cursor-pointer"
                  style="top: 50%; margin-top: -25px;"
                  x-show="products.length">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="50" viewBox="0 0 501.5 501.5"><g><path fill="#2E435A" d="M199.33 410.622l-55.77-55.508L247.425 250.75 143.56 146.384l55.77-55.507L358.44 250.75z"></path></g></svg>
            </span>
            </template>
        </div>
    </template>
</section>
