<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Currency;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * These variables are automatically assigned to any template
 *
 * @var Template $block
 * @var Escaper $escaper
 * @var ViewModelRegistry $viewModels
 */

/**
 * These variables are assigned in the parent templates: grid.phtml, list.phtml and sidebar.phtml
 *
 * @var string $uniqueId
 * @var string $title
 */

/** @var ProductPage $viewModelProducts */
$viewModelProducts = $viewModels->require(ProductPage::class);
$currentProductSku = $viewModelProducts->getProduct() ? $viewModelProducts->getProduct()->getSku() : '';

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var Currency $viewModelCurrency */
$viewModelCurrency = $viewModels->require(Currency::class);

$title = $title ?? __('Recently Viewed Products');


?>
<script>

    function initRecentlyViewedProductsComponent<?= /** @noEscape */$uniqueId ?>(options) {

        const defaultOptions = {
            isSlider: false
        };
        const config = Object.assign({}, defaultOptions, options || {});


        function writeRecentlyViewedToStorage(data) {
            hyva.getBrowserStorage().setItem('recently_viewed_products', JSON.stringify(data));
        }

        function readRecentlyViewedFromStorage () {
            const data = hyva.getBrowserStorage().getItem('recently_viewed_products');
            return data ? JSON.parse(data) : [];
        }

        function removeExpiredProductsInLocalStorage() {
            const updatedLocalStorageData = [];
            readRecentlyViewedFromStorage().forEach(productData => {
                if(productData.expiry > Date.now()){
                    updatedLocalStorageData.push(productData);
                }
            });
            writeRecentlyViewedToStorage(updatedLocalStorageData);
        }

        function isProductInRecentlyViewed(productData) {
            return readRecentlyViewedFromStorage()
                .filter(record => record.sku === productData.sku)
                .length > 0;
        }

        function addCurrentProductToRecentlyViewed() {
            const currentProduct = createRecordForCurrentProduct();

            if (currentProduct.sku !== '' && !isProductInRecentlyViewed(currentProduct)) {
                const recentlyViewedSkusArray = readRecentlyViewedFromStorage();
                recentlyViewedSkusArray.push(currentProduct);
                writeRecentlyViewedToStorage(recentlyViewedSkusArray);
            }
        }

        function createRecordForCurrentProduct() {
            return {
                sku: '<?= $escaper->escapeJs($currentProductSku) ?>',
                expiry: Date.now() + <?= (int) $viewModelProducts->getRecentlyViewedLifeTime() ?> * 1000
            }
        }

        removeExpiredProductsInLocalStorage();
        addCurrentProductToRecentlyViewed();

        return {
            active: 0,
            products: [],
            currency: [],
            currentProductSku: '<?= $escaper->escapeJs($currentProductSku) ?>',
            noOfProductsToShow: <?= (int) $block->getData('page_size') ?>,
            loading: true,
            minHeight() {
                return 'min-height: ' + ((this.loading && '491px') || 0);
            },
            query: '',
            getProducts($nextTick) {
                let itemsToFetch = [];
                const recentlyViewedProductsArray = readRecentlyViewedFromStorage();
                if (recentlyViewedProductsArray.length > 0) {

                    /* Avoid showing the current product */
                    itemsToFetch = recentlyViewedProductsArray
                        .map(productData => productData.sku)
                        .filter(sku => sku !== this.currentProductSku);
                }

                if (!itemsToFetch.length) {
                    this.noOfProductsToShow = 0;
                } else {
                    itemsToFetch = itemsToFetch.slice(0, this.noOfProductsToShow);
                }

                this.query = `{
                        products(
                            filter: {
                                sku: { in: ${JSON.stringify(itemsToFetch)} },
                            }
                            pageSize: ${this.noOfProductsToShow},
                        ) {
                            items {
                                sku
                                id
                                name
                                small_image {
                                    label
                                    url
                                }
                                url_key
                                url_suffix
                                visibility
                                status
                                price_range {
                                        minimum_price {
                                        regular_price {
                                            value
                                            currency
                                        }
                                        final_price {
                                            value
                                            currency
                                        }
                                    }
                                }
                            }
                        }
                    }`;

                window.fetch('/graphql?' + new URLSearchParams({query: this.query}), {
                    method: 'GET',
                    headers: {
                        'Store': '<?= $escaper->escapeJs($viewModelStore->getStoreCode()) ?>',
                        'Content-Currency': '<?= $escaper->escapeJs($viewModelCurrency->getCurrentCurrencyCode()) ?>'
                    },
                })
                    .then((response) =>  response.json())
                    .then((result) => {
                            this.currency = (result &&
                                result.data &&
                                result.data.currency);

                            const responseProducts = (
                                result &&
                                result.data &&
                                result.data.products &&
                                result.data.products.items
                            ) || [];

                            // fix sorting of the response-products according to the sorting of the requested-products
                            const sortedProducts = [];
                            itemsToFetch.forEach(function myFunction(sku,key){
                                responseProducts.forEach(function myFunction(productData,index){
                                    if(sku === productData.sku){
                                        sortedProducts[key] = productData;
                                    }
                                });
                            });
                            return this.products = sortedProducts;
                        }
                    )
                    .finally(() => {
                        this.loading = false;
                        if (config.isSlider) {
                            $nextTick
                                ? $nextTick(() => this.calcPageSize())
                                : setTimeout(() => this.calcPageSize(), 1);
                        }
                    });
            }, // end getProducts()

            addToWishlist(productId) {
                fetch(BASE_URL + "wishlist/index/add/", {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": new URLSearchParams({form_key: hyva.getFormKey(), product: productId, uenc: btoa(window.location.href)}),
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                            [{
                                type: "warning",
                                text: "<?= $escaper->escapeHtml(__('Could not add item to wishlist.')) ?>"
                            }], 5000
                        );
                    }
                }).then(response => {
                    if (!response) { return }
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: (response.success) ? "success" : "error",
                            text: (response.success)
                                ? "<?= $escaper->escapeHtml(
                                    __("%1 has been added to your Wish List.", __("Product"))
                                ) ?>" : response.error_message
                        }], 5000
                    );
                    window.dispatchEvent(new CustomEvent("reload-customer-section-data"));
                }).catch(function (error) {
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: error
                        }], 5000
                    );
                });
            }, // end addToWishlist()

            addToCompare(productId) {
                fetch(BASE_URL + 'catalog/product_compare/add/', {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": new URLSearchParams({form_key: hyva.getFormKey(), product: productId, uenc: btoa(window.location.href)}),
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    }
                }).catch(error => {
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: error
                        }], 5000
                    );
                });
            },
            getSlider() {
                return this.$el.querySelector('.js_slides');
            },
            pageSize: 1,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.products.length / this.pageSize)
                    ) - this.products.length;
                }
            },
            calcActive() {
                const slider = this.getSlider();
                if (slider) {
                    this.active = Math.ceil(
                        Math.round(
                            slider.scrollLeft / (slider.scrollWidth / this.products.length)
                        ) / this.pageSize
                    ) * this.pageSize;
                }
            }
        }
    }

</script>
