<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Store;
use Magento\Catalog\Block\Product\ReviewRendererInterface as ProductReviewRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

$viewMode = 'grid';
$imageDisplayArea = 'category_page_grid';
$showDescription = false;

$name = (string) $block->getName();
$title = (string) $block->getTitle();
$headingTag = $block->getData('heading_tag') ?: 'h3';
$items = $block->getItems() ?? [];
if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return '';
}

$sliderIndex = 1;
$sliderItemRenderer = $block->getLayout()->getBlock('product_list_item')
    ?: $block->getChildBlock('slider.item.template')
    ?: $block->getLayout()->createBlock(Template::class);

$hideRatingSummary = (bool) $block->getData('hide_rating_summary');
$hideDetails       = (bool) $block->getData('hide_details');

$sliderItemRenderer->setData('hide_details', $hideDetails);
$sliderItemRenderer->setData('hide_rating_summary', $hideRatingSummary);

// The slider item renderer block is often a shared instance.
// If a specific item template is set for this slider, the previously set template must be reset later
// so the item template is only replaced for the one slider it is specified on.
$sharedItemRendererTemplate = null;
$isSharedItemRenderer       = $sliderItemRenderer !== $block->getChildBlock('slider.item.template');
if ($isSharedItemRenderer && $block->getChildBlock('slider.item.template')) {
    $sharedItemRendererTemplate = $sliderItemRenderer->getTemplate();
    $sliderSpecificItemTemplate = $block->getChildBlock('slider.item.template')->getTemplate();
    $sliderItemRenderer->setTemplate($sliderSpecificItemTemplate);
}

// The number of slides visible on the xl breakpoint
$maxVisibleSlides = $block->getData('max_visible') ?? 4;

// Breakpoints for 1 visible slider items on mobile, 2 visible on md, 3 on lg and 4 on xl (see $sliderPageSize).
$defaultSliderItemClasses = 'md:w-1/2 lg:w-1/3 xl:w-1/4';

$sliderSectionClasses = $block->getData('maybe_purged_tailwind_section_classes') ?? 'my-12 text-gray-700 body-font';
$slideItemClasses = $block->getData('maybe_purged_tailwind_slide_item_classes') ?? $defaultSliderItemClasses;

?>
<script>
    'use strict';

    function initSliderComponent() {
        return {
            active: 0,
            itemCount: 0,
            getSlider() {
                return this.$root.querySelector('.js_slides');
            },
            pageSize: 4,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.itemCount = slider.querySelectorAll('.js_slide').length;
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                    ) - this.itemCount;
                }
            },
            calcActive() {
                const slider = this.getSlider();
                if (slider) {
                    const sliderItems = this.itemCount + this.pageFillers;
                    const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                    this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                }
            },
            scrollPrevious() {
                this.scrollTo(this.active - this.pageSize);
            },
            scrollNext() {
                this.scrollTo(this.active + this.pageSize);
            },
            scrollTo(idx) {
                if (idx instanceof Event) {
                    idx = this.$el.dataset.index;
                }
                const slider = this.getSlider();
                if (slider) {
                    const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                    slider.scrollLeft = Math.floor(slideWidth) * idx;
                    this.active = idx;
                }
            },
            skipCarouselToNavigation() {
                const element = document.getElementById(this.sliderNavId())
                if (element) {
                    element.scrollIntoView({behavior: 'smooth', block: 'end'});
                    const button = element.querySelector('button:not([disabled])');
                    this.$nextTick(() => button && button.focus({preventScroll: true}))
                }
            },
            getIdPrefixes() {
                return ['slider-nav', 'slider-desc', 'slider-id'];
            },
            onResize() {
                this.calcPageSize();
                this.$nextTick(() => this.calcActive());
            },
            sliderNavId() {
                return this.$id('slider-nav');
            },
            isItemCountGtPageSize() {
                return this.itemCount > this.pageSize;
            },
            sliderItemAriaDescribedById() {
                const productId = this.$el.dataset.productId;
                return `slide-desc-${productId}-${this.$id('slider-id')}`
            },
            dummySliderItemClasses() {
                const index = this.$el.dataset.index;
                return {
                    'js_dummy_slide w-full flex-none <?= $escaper->escapeJs($slideItemClasses) ?>': this.pageFillers > index
                };
            },
            isPreviousSlideButtonDisabled() {
              return this.active === 0;
            },
            previousSlideButtonClasses() {
                return {
                    'opacity-25 pointer-events-none': this.active === 0
                }
            },
            scrollToSlideButtonClasses() {
                const index = this.$el.dataset.index ? parseInt(this.$el.dataset.index) : 0;
                return {
                    'hidden': (this.pageSize !== 1 && !!(index % this.pageSize))
                };
            },
            scrollToSlideButtonAriaCurrent() {
                const currentIndex = this.$el.dataset.index ? parseInt(this.$el.dataset.index) : 0;
                return this.active === currentIndex;
            },
            scrollToSlideButtonAriaLabel() {
                return hyva.str('<?= $escaper->escapeJs(__('Display slide %1')) ?>', (this.$el.dataset.index / this.pageSize) + 1);
            },
            bulletClasses() {
                const dataIndex = this.$el.closest('[data-index]').dataset.index;
                const index = dataIndex ? parseInt(dataIndex) : 0;

                return {
                    'bg-opacity-100': this.active === index,
                    'bg-opacity-25': this.active !== index,
                    'hidden': (this.pageSize !== 1 && !!(index % this.pageSize))
                };
            },
            isNextSlideButtonDisabled() {
                return this.active >= this.itemCount - this.pageSize;
            },
            nextSlideButtonClasses() {
                return {
                    'opacity-25 pointer-events-none': this.isNextSlideButtonDisabled()
                }
            },
            showDummySlide() {
                return this.pageFillers > this.$el.dataset.dummySlideNumber;
            },
        }
    }

    window.addEventListener('alpine:init', () => Alpine.data('initSliderComponent', initSliderComponent), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
<section
    class="<?= $escaper->escapeHtmlAttr($sliderSectionClasses) ?>"
    x-data="initSliderComponent"
    x-init="calcPageSize"
    x-id="getIdPrefixes"
    @resize.window.debounce="onResize"
    aria-roledescription="<?= $escaper->escapeHtmlAttr(__('Carousel')) ?>"
    <?php if ($title): ?>
        aria-labelledby="<?= $escaper->escapeHtmlAttr($name) ?>-slider-title"
    <?php else: ?>
        aria-label="<?= $escaper->escapeHtmlAttr($name) ?>"
    <?php endif; ?>
    x-defer="intersect"
>
    <?php if ($items): ?>
        <div class="relative">
            <?php if ($title): ?>
                <div class="flex flex-col items-center pt-6 pb-3 px-6 mx-auto mb-6 border-b-2
                    border-gray-300 md:flex-row">
                    <<?= /* @noEscape */ $headingTag ?>
                        id="<?= $escaper->escapeHtmlAttr($name) ?>-slider-title"
                        class="text-2xl font-medium text-gray-900 title-font"
                    >
                        <?= $escaper->escapeHtml($title); ?>
                    </<?= /* @noEscape */ $headingTag ?>>
                </div>
            <?php endif; ?>
            <a
                href="#<?= $escaper->escapeHtmlAttr($name) ?>-slider-end"
                class="action skip sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white"
            >
                <?= $escaper->escapeHtml(__('Press to skip carousel')) ?>
            </a>
            <div class="flex-none relative w-full">
                <div class="relative flex flex-nowrap -mx-1 overflow-auto js_slides snap"
                     @scroll.debounce="calcActive"
                     id="<?= $escaper->escapeHtmlAttr($name) ?>-slider-track"
                     aria-live="polite"
                >
                    <?php foreach ($items as $product): ?>
                        <div class="js_slide flex shrink-0 w-full p-1 <?= $escaper->escapeHtmlAttr($slideItemClasses) ?>"
                             data-slider-index="<?= (int) $sliderIndex ?>"
                             data-product-id="<?= $escaper->escapeHtmlAttr($product->getId()) ?>"
                             role="group"
                             aria-roledescription="slide"
                             aria-label="<?= $escaper->escapeHtmlAttr(__('%1 of %2', $sliderIndex, count($items))) ?>"
                        >
                            <?= /** @noEscape */ $productListItemViewModel->getItemHtmlWithRenderer(
                                $sliderItemRenderer,
                                $product,
                                $block,
                                $viewMode,
                                ProductReviewRenderer::SHORT_VIEW,
                                $imageDisplayArea,
                                $showDescription
                            ) ?>
                        </div>
                        <?php $sliderIndex++ ?>
                    <?php endforeach; ?>
                    <?php for ($i = 0; $i < $maxVisibleSlides; $i++): /* Add empty filler slides in case the number of items is not dividable by the pagesize */ ?>
                        <div
                            class="js_dummy_slide w-full shrink-0 <?= $escaper->escapeHtmlAttr($slideItemClasses) ?>"
                            aria-hidden="true"
                            data-dummy-slide-number="<?= (int)$i; ?>"
                            x-show="showDummySlide"
                            x-cloak
                        ></div>
                    <?php endfor; ?>
                </div>
            </div>
            <div style="min-height: 76px">
            <template x-if="isItemCountGtPageSize">
                <div class="flex items-center justify-center py-4">
                    <button
                        type="button"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Previous slide')) ?>"
                        :disabled="isPreviousSlideButtonDisabled"
                        class="text-black flex-none p-3"
                        :class="previousSlideButtonClasses"
                        @click="scrollPrevious"
                    >
                        <?= $heroicons->chevronLeftHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                    </button>
                    <div class="flex flex-wrap w-full md:w-auto justify-center">
                    <?php for ($i=0; $i < $itemCount; $i++): ?>
                        <button
                            type="button"
                            data-index="<?= (int) $i ?>"
                            :class="scrollToSlideButtonClasses"
                            :aria-current="scrollToSlideButtonAriaCurrent"
                            :aria-label="scrollToSlideButtonAriaLabel"
                            @click="scrollTo"
                        >
                            <span
                                class="shrink-0 block w-3 h-3 m-4 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                :class="bulletClasses"
                                @click="scrollTo"
                            ></span>
                        </button>
                    <?php endfor; ?>
                    </div>
                    <button
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Next slide')) ?>"
                        :disabled="isNextSlideButtonDisabled"
                        class="text-black flex-none p-3"
                        :class="nextSlideButtonClasses"
                        @click="scrollNext"
                     >
                        <?= $heroicons->chevronRightHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                    </button>
                </div>
            </template>
            </div>
            <span id="<?= $escaper->escapeHtmlAttr($name) ?>-slider-end" tabindex="-1"></span>
        </div>
    <?php endif; ?>
</section>
<?php

if ($sharedItemRendererTemplate) {
    $sliderItemRenderer->setTemplate($sharedItemRendererTemplate);
}

?>
