<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\MagentoMetadata;

/** @var HyvaCsp $hyvaCsp */

/** @var ViewModelRegistry $viewModels */
$magento = $viewModels->require(MagentoMetadata::class);

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<script>
    function initGrandTotalSegment() {
        return {
            isGrandTotalAndIncl() {
                return this.segment.code === 'grand_total' && window.checkoutConfig.includeTaxInGrandTotal;
            },
            isGrandTotalAndExcl() {
                return this.segment.code === 'grand_total' && !window.checkoutConfig.includeTaxInGrandTotal;
            },
            formatGrandTotal() {
                return hyva.formatPrice(this.segment.value);
            },
            formatGrandTotalExclTax() {
                <?php /* All Mage-OS releases with a version < 2.4.6 match Magento code >= 2.4.6 */ ?>
                <?php if ($magento->versionCompare('<', '2.4.6') && $magento->getDistributionName() === 'Magento'): ?>
                return hyva.formatPrice(this.totalsData.grand_total);
                <?php else: ?>
                return hyva.formatPrice(totalsData.grand_total - totalsData.tax_amount);
                <?php endif; ?>
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initGrandTotalSegment', initGrandTotalSegment), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
