<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Link $block */
?>
<?php if ($block->isPossibleOnepageCheckout()): ?>
    <a @click.prevent.stop="proceedToCheckout"
        href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getCheckoutUrl())) ?>"
        title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
        class="checkout my-4 btn btn-primary btn-size-lg justify-center"
        id="checkout-link-button"
    >
        <?= $escaper->escapeHtml(__('Proceed to Checkout')) ?>
    </a>
<?php endif ?>
