<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<div x-data="initDiscountTotalSegment">
<template x-if="isDiscountSegment" data-total-code="discount">
    <div :class="wrapperClass">
        <div x-text="formatTotalLabel"></div>
        <div x-text="formatDiscountValue" class="justify-self-end"></div>
    </div>
</template>
</div>
