<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\MagentoMetadata;

/** @var ViewModelRegistry $viewModels */
$magento = $viewModels->require(MagentoMetadata::class);

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display subtotal excluding tax -->
<div x-data="initGrandTotalSegment">
<template x-if="isGrandTotalAndIncl">
    <div class="divide-y">
        <div :class="wrapperClassTotals">
            <div x-text="formatTotalLabelInclTax"></div>
            <div x-text="formatGrandTotal" class="justify-self-end"></div>
        </div>

        <div :class="wrapperClass" class="text-base">
            <div x-html="formatTotalLabelExclTax"></div>
            <div x-text="formatGrandTotalExclTax" class="justify-self-end"
            ></div>
        </div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="isGrandTotalAndExcl">
    <div :class="wrapperClassTotals">
        <div x-text="formatTotalLabel"></div>
        <div :data-amount="segment.value" x-text="formatGrandTotal" class="justify-self-end"></div>
    </div>
</template>
</div>
