<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!-- display subtotal excluding tax -->
<div x-data="initGrandTotalSegment">
<template x-if="isGrandTotalAndIncl">
    <div>
        <div class="flex py-2 pt-6 my-2 mx-auto text-xl md:grid md:grid-cols-2 md:w-full border-b border-container">
            <div class="w-7/12 font-semibold text-left md:w-auto"
                 x-html="formatTotalLabelInclTax"
            ></div>
            <div class="w-5/12 text-right md:w-auto"
                 x-text=formatGrandTotal"
            ></div>
        </div>

        <div class="flex py-2 my-2 mx-auto mb-12 text-md md:grid md:grid-cols-2 md:w-full">
            <div class="w-7/12 font-semibold text-left md:w-auto"
                 x-html="formatTotalLabelExclTax"
            ></div>
            <div class="w-5/12 text-right md:w-auto"
                 x-text="formatGrandTotalExclTax"
            ></div>
        </div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="isGrandTotalAndExcl">
    <div class="flex py-2 pt-6 my-2 mx-auto mb-12 text-2xl md:grid md:grid-cols-2 md:w-full">

        <div class="w-7/12 font-semibold text-left md:w-auto"
             x-html="formatTotalLabel"
        ></div>
        <div class="w-5/12 text-right md:w-auto"
             :data-amount="segment.value"
             x-text="formatGrandTotal"
        ></div>
    </div>
</template>
</div>
