<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<div x-data="initShippingTotalSegment">
<!-- display shipping including and excluding tax -->
<template x-if="isShippingSegmentAndDisplayBoth">
    <div :class="wrapperClass">
        <div x-text="formatTotalLabelExclTax"></div>
        <div :data-amount="formatShippingAmount" class="justify-self-end"></div>
        <div x-text="formatTotalLabelInclTax"></div>
        <div x-text="formatShippingInclTax" class="justify-self-end"></div>>
    </div>
</template>

<!-- display shipping excluding tax -->
<template x-if="isShippingSegmentAndDisplayExcl">
    <div :class="wrapperClass">
        <div x-text="formatTotalLabel"></div>
        <div x-text="formatShippingTotalValue" class="justify-self-end"></div>
    </div>
</template>

<!-- display shipping including tax -->
<template x-if="isShippingSegmentAndDisplayIncl">
    <div :class="wrapperClass">
        <div x-text="formatTotalLabel"></div>
        <div x-text="formatShippingInclTax" class="justify-self-end"></div>
    </div>
</template>
</div>
