<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<!-- display subtotal including and excluding tax -->
<div x-data="initSubtotalSegment">
<template x-if="isSubtotalSegmentAndDisplayBoth">
    <div :class="wrapperClass">
        <div x-html="formatTotalLabelExclTax"></div>
        <div x-text="formatSubtotal" class="justify-self-end"></div>
        <div x-html="formatTotalLabelInclTax"></div>
        <div x-text="formatSubtotalInclTax" class="justify-self-end"></div>
    </div>
</template>

<!-- display subtotal excluding tax -->
<template x-if="isSubtotalSegmentAndDisplayExcl">
    <div :class="wrapperClass">
        <div x-html="formatTotalLabel"></div>
        <div x-text="formatSubtotal" class="justify-self-end"></div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="isSubtotalSegmentAndDisplayIncl">
    <div :class="wrapperClass">
        <div x-html="formatTotalLabel"></div>
        <div :data-amount="totalsData.subtotal_incl_tax" x-text="formatSubtotalInclTax" class="justify-self-end"></div>
    </div>
</template>
</div>
