<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\ViewModel\HyvaCsp;

/** @var HyvaCsp $hyvaCsp */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<script>
    function initTaxSegment() {
        return {
            taxSummaryIsOpen: false,
            isTaxSegmentVisible() {
                return this.segment.code === 'tax' && (this.segment.value > 0 || window.checkoutConfig.isZeroTaxDisplayed);
            },
            isTaxSummaryVisible() {
                return this.segment.value > 0 && window.checkoutConfig.isFullTaxSummaryDisplayed;
            },
            isTaxSummaryHidden() {
                return ! this.isTaxSegmentVisible()
            },
            toggle() {
                this.taxSummaryIsOpen = ! this.taxSummaryIsOpen;
            },
            summaryCssClasses() {
                return {
                    'rotate-180': this.taxSummaryIsOpen
                };
            },
            formatTaxRateLabel() {
                return `${this.taxRate.title} (${this.taxRate.percent}%)`;
            },
            formatTaxTotal() {
                return hyva.formatPrice(this.segment.value);
            },
            formatTaxDetailAmount() {
                return hyva.formatPrice(this.taxItem.amount);
            }
        };
    }
    window.addEventListener('alpine:init', () => Alpine.data('initTaxSegment', initTaxSegment), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
<div x-data="initTaxSegment">
<template x-if="isTaxSegmentVisible">
    <div>
        <template x-if="isTaxSummaryHidden">
            <div class="flex pb-2 my-2 border-b text-md lg:text-sm md:grid md:grid-cols-2 md:w-full border-container">
                <div class="w-7/12 text-left md:w-auto"
                     x-html="formatTotalLabel"
                ></div>
                <div class="w-5/12 text-right md:w-auto"
                     x-text="formatTaxTotal"
                ></div>
            </div>
        </template>

        <template x-if="isTaxSummaryVisible">
            <div class="flex pb-2 my-2 border-b text-md lg:text-sm md:grid md:grid-cols-2 md:w-full border-container cursor-pointer"
                @click="toggle">
                <div class="w-7/12 text-left md:w-auto items-center"
                     x-html="formatTotalLabel"
                ></div>
                <div class="w-5/12 text-right justify-end items-center md:w-auto flex">
                    <span
                        x-text="formatTaxTotal"></span>

                    <span :class="summaryCssClasses" class="block transform rotate-180">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-6 h-6" width="25" height="25">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                        </svg>
                    </span>

                </div>
                <div x-show="taxSummaryIsOpen" class="col-span-2">
                    <template x-for="(taxItem, index) in segment.extension_attributes.tax_grandtotal_details" :key="index">
                        <div class="flex px-2 py-2 my-2 border-t border-b last:border-b-0 last:pb-0 text-md lg:text-sm md:grid md:grid-cols-2 md:w-full border-container">
                            <div class="w-7/12 text-left md:w-auto">
                                <template x-for="(taxRate, index) in taxItem.rates">
                                    <div x-html="formatTaxRateLabel"></div>
                                </template>
                            </div>
                            <div class="w-5/12 text-right md:w-auto"
                                 x-text="formatTaxDetailAmount"
                            ></div>
                        </div>
                    </template>
                </div>
            </div>
        </template>
    </div>
</template>
</div>
