<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */

?>
<div class="gift-message">
    <div class="gift-options-content">
        <fieldset class="space-y-4">
            <div class="field" x-id="getIdPrefixRecipient">
                <label :for="getIdRecipient"><?= $escaper->escapeHtml(__('To:')) ?></label>
                <div class="control">
                    <input
                        :id="getIdRecipient"
                        :value="formMessage.recipient"
                        type="text"
                        @input="onInputRecipient"
                        @keydown.enter.prevent="submitGiftOption"
                        class="form-input w-full"
                    >
                </div>
            </div>

            <div class="field" x-id="getIdPrefixSender">
                <label :for="getIdSender">
                    <span><?= $escaper->escapeHtml(__('From:')) ?></span>
                </label>
                <div class="control">
                    <input
                        :id="getIdSender"
                        :value="formMessage.sender"
                        type="text"
                        @input="onInputSender"
                        @keydown.enter.prevent="submitGiftOption"
                        class="form-input w-full"
                    >
                </div>
            </div>

            <div class="field required" x-id="getIdPrefixMessage">
                <label :for="getIdMessage">
                    <span><?= $escaper->escapeHtml(__('Message')) ?></span>
                </label>
                <div class="control">
                    <textarea
                        :id="getIdMessage"
                        @input="onInputMessage"
                        class="form-input w-full"
                        rows="5"
                        cols="10"
                        x-text="formMessage.message"
                    ></textarea>
                </div>
            </div>
        </fieldset>
    </div>
</div>
