<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */

?>
<div class="gift-message">
    <div class="gift-options-title my-4">
        <span>
             <?= $escaper->escapeHtml(__('Gift Message (optional)')) ?>
        </span>
    </div>
    <div class="gift-options-content">
        <fieldset class="fieldset">
            <div class="field field-to" x-id="getIdPrefixRecipient">
                <label
                    :for="getIdRecipient"
                    class="label"
                >
                    <span><?= $escaper->escapeHtml(__('To:')) ?></span>
                </label>
                <div class="control">
                    <input
                        :id="getIdRecipient"
                        :value="formMessage.recipient"
                        type="text"
                        @input="onInputRecipient"
                        @keydown.enter.prevent="submitGiftOption"
                        class="form-input w-full disabled:opacity-75 disabled:bg-gray-100 disabled:pointer-events-none"
                    >
                </div>
            </div>

            <div class="field field-from" x-id="getIdPrefixSender">
                <label
                    :for="getIdSender"
                    class="label"
                >
                    <span><?= $escaper->escapeHtml(__('From:')) ?></span>
                </label>
                <div class="control">
                    <input
                        :id="getIdSender"
                        :value="formMessage.sender"
                        type="text"
                        @input="onInputSender"
                        @keydown.enter.prevent="submitGiftOption"
                        class="form-input w-full disabled:opacity-75 disabled:bg-gray-100 disabled:pointer-events-none"
                    >
                </div>
            </div>
            <div class="field text" x-id="getIdPrefixMessage">
                <label :for="getIdMessage" class="label">
                    <span><?= $escaper->escapeHtml(__('Message')) ?></span>
                </label>
                <div class="control">
                    <textarea
                        :id="getIdMessage"
                        @input="onInputMessage"
                        class="form-input w-full disabled:opacity-75 disabled:bg-gray-100 disabled:pointer-events-none"
                        rows="5"
                        cols="10"
                        x-text="formMessage.message"
                    >
                    </textarea>
                </div>
            </div>
        </fieldset>
    </div>
</div>
