<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\GiftMessage\Block\Cart\GiftOptions;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Escaper $escaper */
/** @var GiftOptions $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);

$slideOutDrawer = (bool) $block->getSlideOutDrawer();

$uniqueId = uniqid();
?>

<script>
    function giftOptions_<?= /** @noEscape */ $uniqueId ?>() {
        'use strict';
        return {
            inSlideOut: <?= $slideOutDrawer ? 'true' : 'false' ?>,
            isLoading: false,
            formBlockVisibility: false,
            resultBlockVisibility: false,
            hasActiveOptions: false,
            itemId: 'orderLevel',
            isGiftMsgEnabled: window.giftOptionsConfig.isOrderLevelGiftOptionsEnabled,
            formMessage: {
                recipient: null,
                sender: null,
                message: null,
                alreadyAdded: null,
            },
            savedFormMessage: {
                recipient: null,
                sender: null,
                message: null,
                alreadyAdded: null,
            },
            extensionAttributes: {},
            initialize() {
                const message = window.giftOptionsConfig.giftMessage.hasOwnProperty(this.itemId) ?
                    window.giftOptionsConfig.giftMessage[this.itemId] : null;
                const isObject = Object.prototype.toString.call(message) == '[object Object]';

                if (isObject) {
                    this.savedFormMessage.recipient = message.recipient;
                    this.savedFormMessage.sender = message.sender;
                    this.savedFormMessage.message = message.message;
                    this.savedFormMessage.alreadyAdded = true;
                    this.formMessage = Object.assign({}, this.savedFormMessage);
                    this.resultBlockVisibility = true;
                }

                <?php if ($slideOutDrawer): ?>
                    const onDrawerToggle = () => {
                        if (this.formBlockVisibility) {
                            document.body.style.overflow = 'hidden';
                        } else {
                            document.body.style.overflow = null;
                        }
                    }
                    this.$watch('formBlockVisibility', value => onDrawerToggle(value));
                <?php endif ?>

                window.addEventListener('addional-gift-options-loaded-' + this.itemId, (e) => {
                    if (this.hasActiveOptions) return;

                    if (e.detail.isOrderLevelGiftOptionsEnabled) this.hasActiveOptions = true;
                });

                window.addEventListener('addional-gift-options-results-' + this.itemId, (e) => {
                    if (this.resultBlockVisibility) return;

                    this.resultBlockVisibility = e.detail.hasResults;
                });

                window.addEventListener('update-gift-options-extension-attributes-' + this.itemId, (e) => {
                    this.extensionAttributes = {
                        ...this.extensionAttributes,
                        ...e.detail
                    };
                });
            },

            submitGiftOption() {
                let endPoint;
                const restBaseUrl = BASE_URL + 'rest/' + CURRENT_STORE_CODE + '/V1/';

                window.dispatchEvent(new CustomEvent('before-gift-options-submit-' + this.itemId, {
                    detail: {}
                }))

                if (window.giftOptionsConfig.isCustomerLoggedIn) {
                    endPoint = restBaseUrl + 'carts/mine/gift-message';
                } else {
                    endPoint = restBaseUrl + 'guest-carts/' + window.giftOptionsConfig.quoteId + '/gift-message';
                }

                this.isLoading = true;

                fetch(endPoint, {
                    method: 'post',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    body: JSON.stringify({
                        gift_message: {
                            recipient: this.formMessage.recipient,
                            sender: this.formMessage.sender,
                            message: this.formMessage.message,
                            extension_attributes: this.extensionAttributes
                        }
                    }),
                }).then(response => {
                    if (response.ok) {
                        return response.json();
                    } else {
                        console.warn("GET request failed", response);
                    }
                }).then(() => {
                    this.savedFormMessage = Object.assign({}, this.formMessage);
                    document.querySelector('form[action*="checkout/cart/updatePost/"]').submit()
                });
            }
        }
    }
</script>
<div x-data="giftOptions_<?= /** @noEscape */ $uniqueId ?>()" x-init="initialize" class="gift-options-component w-full flex flex-wrap my-6" :data-item-id="itemId" x-cloak>
    <?= $block->getChildHtml('loading') ?>
    <div class="text-left gift-options-title w-full order-first" x-show="isGiftMsgEnabled || hasActiveOptions">
        <span @click="formBlockVisibility = !formBlockVisibility" class="cursor-pointer text-primary-lighter select-none whitespace-nowrap underline">
            <?= $escaper->escapeHtml(__('Gift options')) ?>
            <?php if (!$slideOutDrawer): ?>
                <span x-show="!formBlockVisibility">
                    <?= $heroicons->chevronDownHtml('inline-block', 16, 16) ?>
                </span>
                <span x-show="formBlockVisibility">
                    <?= $heroicons->chevronUpHtml('inline-block', 16, 16) ?>
                </span>
            <?php endif ?>
        </span>
    </div>
    <?php if ($slideOutDrawer): ?>
        <div role="dialog"
            aria-labelledby="enquiry-form-drawer-title"
            aria-modal="true"
            class="fixed inset-y-0 right-0 z-30 flex max-w-full"
            @keydown.window.escape="formBlockVisibility=false"
        >
            <div class="backdrop"
                x-show="formBlockVisibility"
                x-transition:enter="ease-in-out duration-500"
                x-transition:enter-start="opacity-0"
                x-transition:enter-end="opacity-100"
                x-transition:leave="ease-in-out duration-500"
                x-transition:leave-start="opacity-100"
                x-transition:leave-end="opacity-0"
                @click="formBlockVisibility=false"
                aria-label="Close panel"
            ></div>
            <div class="relative w-screen max-w-md shadow-2xl bg-white p-8 flex flex-col overflow-y-auto"
                x-show="formBlockVisibility"
                x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
                x-transition:enter-start="translate-x-full"
                x-transition:enter-end="translate-x-0"
                x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
                x-transition:leave-start="translate-x-0"
                x-transition:leave-end="translate-x-full"
            >
                <div class="relative">
                    <h2 class="text-lg font-medium leading-7 text-gray-900 "><?= $escaper->escapeHtml('Order Gift Options') ?></h4>
                        <div class="absolute top-0 right-0 cursor-pointer" @click="formBlockVisibility=false" aria-label="Close panel" tabindex="0" role="button">
                            <?= $heroicons->xHtml('inline-block', 24, 24) ?>
                        </div>
                </div>
                <?= $block->getChildHtml('gift-options-body') ?>
            </div>
        </div>
    <?php else: ?>
        <?= $block->getChildHtml('gift-options-body') ?>
    <?php endif ?>
    <div x-show="(resultBlockVisibility && !formBlockVisibility) || (resultBlockVisibility && inSlideOut)" class="gift-summary pt-2" @click="formBlockVisibility = true">
        <div class="additional-options-summary"></div>
        <div x-show="savedFormMessage.message">
            <span><?= $escaper->escapeHtml(__('Message:')) ?></span><span x-text="savedFormMessage.message"></span>
        </div>
    </div>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag(
    'script',
    [],
    'window.giftOptionsConfig = ' . /* @noEscape */ $block->getGiftOptionsConfigJson(),
    false
) ?>
