<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\ViewModel\HyvaCsp;

/** @var HyvaCsp $hyvaCsp */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<script>
    function initDiscountTotalSegment() {
        return {
            isDiscountSegment() {
                return this.segment.code === 'discount';
            },
            formatDiscountAmount() {
                return hyva.formatPrice(this.segment.value);
            }
        };
    }
    window.addEventListener('alpine:init', () => Alpine.data('initDiscountTotalSegment', initDiscountTotalSegment), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
<div x-data="initDiscountTotalSegment">
<template x-if="isDiscountSegment">
    <div class="flex pb-2 my-2 border-b text-md lg:text-sm md:grid md:grid-cols-2 md:w-full border-container">
        <div class="w-7/12 text-left md:w-auto"
             x-html="formatTotalLabel"
        ></div>
        <div class="w-5/12 text-right md:w-auto"
             x-text="formatDiscountAmount"
        ></div>
    </div>
</template>
</div>
