<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div x-data="initGrandTotalSegment">
<template x-if="isGrandTotal">
    <div class="flex py-2 pt-6 my-2 mx-auto mb-12 text-2xl md:grid md:grid-cols-2 md:w-full">
        <h3 class="w-7/12 font-semibold text-left md:w-auto"
            x-html="formatTotalLabel"
        ></h3>
        <div class="w-5/12 text-right md:w-auto"
             x-text=formatGrandTotal"
        ></div>
    </div>
</template>
</div>
