<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Search\Block\Term;

/** @var Term $block */
/** @var Escaper $escaper */
?>
<?php if (count($block->getTerms()) > 0): ?>
    <ul
        role="list"
        class="prose my-6 flex flex-wrap items-start"
        style="font-size: clamp(1.5em, 4vw, 3.5em); line-height: 1.2; gap: 0.875em 1em"
    >
        <?php foreach ($block->getTerms() as $term): ?>
            <li style="font-size: <?= $escaper->escapeHtmlAttr($term->getRatio()*70+75) ?>%">
                <a href="<?= $escaper->escapeUrl($block->getSearchUrl($term)) ?>">
                    <?= $escaper->escapeHtml($term->getQueryText()) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p class="my-6">
        <?= $escaper->escapeHtml(__('There are no search terms available.')) ?>
    </p>
<?php endif; ?>
