<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Paypal\Block\Express\InContext\Minicart\SmartButton;

/** @var SmartButton $block */
/** @var Escaper $escaper */

/*
 * This template renders the PayPal in-context shortcut button for the mini-cart and the cart.
 * For the mini-cart, the html is part of the cart.extra_actions private section data, and is injected via JS.
 * The related JS can be found in Magento_Paypal::express/in-context/shortcut/button-js.phtml.
 */

for ($candidate = $block, $isCartPage = false; $candidate && ! $isCartPage; $candidate = $candidate->getParentBlock()) {
    $isCartPage = $candidate->getNameInLayout() === 'checkout.cart.shortcut.buttons';
}
$isMinicart = ! $isCartPage;

$widgetData = json_decode($block->getJsInitParams(), true);
$clientConfig = json_encode($widgetData['Magento_Paypal/js/in-context/button']['clientConfig']);

$renderTargetElementId = sprintf('paypalInContextRenderTarget%d', $isMinicart)

?>
<div x-data="initPayPalInContextButton"
     data-render-target-id="<?= $escaper->escapeHtmlAttr($renderTargetElementId) ?>"
     data-client-config="<?= $escaper->escapeHtmlAttr($clientConfig) ?>"
     data-is-mini-cart="<?= (int) $isMinicart ?>"
     id="<?= $escaper->escapeHtmlAttr($renderTargetElementId) ?>"
     class="paypal checkout paypal-logo min-h-a11y cart-extra-actions-container isolate"
    <?php if ($isMinicart): ?>
     x-init="initMiniCartButtons"
     x-intersect="checkAndInitializeButtons"
    <?php endif; ?>
    <?php if ($isCartPage): ?>
     @private-content-loaded.window="initCartPageButtons"
    <?php endif; ?>
>
</div>
