<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

// phpcs:disable Magento2.Templates.ThisInTemplate

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Cart\ItemOutput;
use Hyva\Theme\ViewModel\Modal;
use Magento\Checkout\Block\Cart\Grid;
use Magento\Checkout\ViewModel\Cart as CartViewModel;
use Magento\Framework\Escaper;

/** @var Grid $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var CartViewModel $cartViewModel */
$cartViewModel = $viewModels->require(CartViewModel::class);

/** @var Modal $modelViewModel */
$modalViewModel = $viewModels->require(Modal::class);

/** @var ItemOutput $cartItemOutputViewModel */
$cartItemOutputViewModel = $viewModels->require(ItemOutput::class);
?>
<?php $mergedCells = ($cartItemOutputViewModel->isItemPriceDisplayBoth() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
      x-data="{}"
      @submit.prevent="hyva.postCart($event.target)"
      method="post"
      id="form-validate"
      class="form form-cart w-full float-left"
>
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <table id="shopping-cart-table"
               class="cart items data table w-full table-row-items"
        >
            <caption class="table-caption sr-only">
                <?= $escaper->escapeHtml(__('Shopping Cart Items')) ?>
            </caption>
            <thead class="hidden lg:table-header-group">
                <tr class="text-right">
                    <th class="col item text-left pt-4 pb-2" scope="col">
                        <?= $escaper->escapeHtml(__('Item')) ?>
                    </th>
                    <th class="col price pt-4 pb-2" scope="col">
                        <?= $escaper->escapeHtml(__('Price')) ?>
                    </th>
                    <th class="col qty pt-4 pb-2" scope="col">
                        <?= $escaper->escapeHtml(__('Qty')) ?>
                    </th>
                    <th class="col subtotal pt-4 pb-2" scope="col">
                        <?= $escaper->escapeHtml(__('Subtotal')) ?>
                    </th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart actions flex flex-col sm:flex-row justify-end gap-4 items-center my-4">
        <?php if ($cartViewModel->isClearShoppingCartEnabled()): ?>
            <div x-data="hyva.modal()">
                <button @click="show" type="button" title="<?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?>"
                    class="action clear" id="empty_cart_button">
                    <span><?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?></span>
                </button>
                <?= /* @noEscape */ $modalViewModel->createModal()->withContent(<<<END_OF_CONTENT
                    <div class="text-lg mb-8">
                        <h2>{$escaper->escapeHtml(__('Are you sure you want to remove all items from your shopping cart?'))}</h2>
                    </div>
                    <div class="mt-20 flex gap-2">
                        <button @click="hide" type="button" class="btn btn-secondary">
                            {$escaper->escapeHtml(__('Cancel'))}
                        </button>
                        <button x-focus
                            type="button"
                            name="update_cart_action"
                            class="btn btn-primary"
                            x-data="{
                                postData: {
                                    action: '{$escaper->escapeUrl($block->getUrl('checkout/cart/updatePost'))}',
                                    data: { update_cart_action: 'empty_cart' }
                                }
                            }"
                            @click.prevent="hyva.postForm(postData);"
                        >
                            {$escaper->escapeHtml(__('OK'))}
                        </button>

                    </div>
                END_OF_CONTENT
                ) ?>
            </div>
        <?php endif ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $escaper->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update btn btn-secondary">
            <span><?= $escaper->escapeHtml(__('Update Shopping Cart')) ?></span>
        </button>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
