<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist;

/** @var MoveToWishlist $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()): ?>
    <button
        type="button"
        class="btn p-2"
        x-data="moveToWishlist"
        data-post-form="<?= $escaper->escapeHtmlAttr($block->getMoveFromCartParams()) ?>"
        @click.prevent='click'
        title="<?= $escaper->escapeHtmlAttr(__('Move to Wishlist')) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Move to Wishlist')) ?>"
    >
        <?= $lucideIcons->heartHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
    </button>
    <script>
        function moveToWishlist() {
            return {
                click() {
                    hyva.postForm(JSON.parse(this.$el.dataset.postForm))
                }
            }
        }
        window.addEventListener('alpine:init', () => Alpine.data('moveToWishlist', moveToWishlist), {once: true})
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>
<?php endif ?>
