<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig('checkout/sidebar/max_items_display_count');

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<script>
    function initCartDrawer() {
        return {
            open: false,
            closed() {
                return !this.open
            },
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int) $maxItemsToDisplay ?>,
            itemsCount: 0,
            cartIsEmpty() {
                return this.itemsCount === 0
            },
            getData() {
                const data = this.$event.detail.data;

                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.setCartItems();
                }
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('<?= $escaper->escapeJs(__('%0 of %1 products in cart displayed')) ?>', this.maxItemsToDisplay, this.itemsCount)
            },
            shouldShowItemCount() {
                return this.maxItemsToDisplay && this.maxItemsToDisplay < this.itemsCount;
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
            },
            deleteItemFromCart() {
                const itemId = this.item.item_id;

                this.isLoading = true;

                const itemData = this.cart.items.filter((item) => item['item_id'] === itemId);
                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'checkout/sidebar/removeItem/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&item_id=" + itemId,
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        window.dispatchMessages && window.dispatchMessages([{
                            type: 'warning',
                            text: '<?= $escaper->escapeJs(__('Could not remove item from quote.')) ?>'
                        }]);
                        this.isLoading = false;
                    }
                }).then(result => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: result.success ? 'success' : 'error',
                        text: result.success
                            ? '<?= $escaper->escapeJs(__('You removed the item.')) ?>'
                            : result.error_message
                    }], result.success ? 5000 : 0);

                    if (result.success && itemData) {
                        window.dispatchEvent(new CustomEvent('cart-item-removed', { detail: itemData }));
                    }

                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            },
            scrollLock(use = true) {
                document.body.style.overflow = use ? "hidden" : "";
            },
            toggleCartDrawer() {
                const event = this.$event;
                if (event.detail && event.detail.isOpen !== undefined) {
                    if (event.detail.isOpen) {
                        this.openCartDrawer();
                    } else {
                        this.open = false;
                        this.scrollLock(false);
                        this.$refs && this.$refs.cartDialogContent && hyva.releaseFocus(this.$refs.cartDialogContent);
                    }
                } else {
                    <?php
                    /*
                     * The toggle-cart event was previously dispatched without parameter to open the drawer (not toggle).
                     * Keeping this in here for backwards compatibility.
                     */
                    ?>
                    this.openCartDrawer()
                }
            },
            openCartDrawer() {
                this.open = true;
                this.scrollLock(true);
                this.$nextTick(() => {
                    this.$refs && this.$refs.cartDialogContent && hyva.trapFocus(this.$refs.cartDialogContent)
                })
            },
            closeCartDrawer() {
                this.$dispatch('toggle-cart', { isOpen: false })
            },
            getSectionDataExtraActions() {
                if (!this.cart.extra_actions) {
                    return '';
                }

                const contentNode = document.createElement('div');
                contentNode.innerHTML = this.cart.extra_actions;

                hyva.activateScripts(contentNode);

                return contentNode.innerHTML;
            },
            cartDialogContentTabIndex() {
                return this.open ? 0 : -1
            },
            productIsVisibleInSite() {
                return this.item.product_has_url && this.item.is_visible_in_site_visibility
            },
            productIsNotVisibleInSite() {
                return !this.productIsVisibleInSite()
            },
            productIsNotGroupedAndVisibleInSite() {
                return this.item.product_type !== 'grouped' && this.item.is_visible_in_site_visibility
            },
            productAriaLabel() {
                return hyva.strf(this.$el.dataset.ariaLabel, this.item.product_name)
            },
            optionLabelText() {
                return this.option.label + ':';
            },
            proceedToCheckout() {
                this.closeCartDrawer()

                this.$dispatch(
                    'toggle-authentication',
                    {
                        url: '<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>'
                    }
                )
            }
        }
    }

    window.addEventListener('alpine:init', () => Alpine.data('initCartDrawer', initCartDrawer), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
<section x-cloak
         x-show="cart"
         id="cart-drawer"
         x-data="initCartDrawer"
         @private-content-loaded.window="getData"
         @toggle-cart.window="toggleCartDrawer"
         @keydown.escape="closeCartDrawer"
>
    <div role="dialog"
         aria-labelledby="cart-drawer-title"
         aria-modal="true"
         :aria-hidden="closed"
         class="fixed inset-y-0 right-0 z-30 flex max-w-full">
        <div class="backdrop"
             x-show="open"
             x-transition:enter="ease-in-out duration-500"
             x-transition:enter-start="opacity-0"
             x-transition:enter-end="opacity-100"
             x-transition:leave="ease-in-out duration-500"
             x-transition:leave-start="opacity-100"
             x-transition:leave-end="opacity-0"
             role="button"
             @click="closeCartDrawer"
             aria-label="<?= $escaper->escapeHtmlAttr(__('Close minicart')) ?>"></div>
        <div class="relative w-screen max-w-md shadow-2xl"
             x-show="open"
             x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
             x-transition:enter-start="translate-x-full"
             x-transition:enter-end="translate-x-0"
             x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
             x-transition:leave-start="translate-x-0"
             x-transition:leave-end="translate-x-full"
             x-ref="cartDialogContent"
             role="region"
             :tabindex="cartDialogContentTabIndex"
             aria-label="<?= $escaper->escapeHtmlAttr(__('My Cart')) ?>"
        >
            <div class="flex flex-col h-full max-h-screen bg-white shadow-xl">
                <?= $block->getChildHtml('cart-drawer.top'); ?>

                <header class="relative px-4 py-6 sm:px-6">
                    <p id="cart-drawer-title" class="text-lg font-medium leading-7 text-gray-900">
                        <strong><?= $escaper->escapeHtml(__('My Cart')) ?></strong>
                        <span class="items-total text-xs"
                              x-show="shouldShowItemCount"
                              x-text="getItemCountTitle">
                        </span>
                    </p>
                </header>

                <?= $block->getChildHtml('cart-drawer.items.before'); ?>

                <template x-if="cartIsEmpty">
                    <div class="relative px-4 py-6 bg-white border-bs sm:px-6 border-container">
                        <?= $escaper->escapeHtml(__('Cart is empty')) ?>
                    </div>
                </template>

                <template x-if="itemsCount">
                    <div class="relative grid gap-6 sm:gap-8 px-1 py-3 sm:px-3 bg-white border-b border-container overflow-y-auto overscroll-y-contain">
                        <template x-for="item in cartItems">
                            <div class="flex items-start p-3 space-x-4 transition duration-150 ease-in-out rounded-lg hover:bg-gray-100">
                                <template x-if="productIsVisibleInSite">
                                    <a :href="item.product_url"
                                       class="w-1/4 !ml-0"
                                       data-aria-label="<?= $escaper->escapeHtmlAttr(__('Product "%0"')) ?>"
                                       :aria-label="productAriaLabel"
                                    >
                                        <img
                                            :src="item.product_image.src"
                                            :width="item.product_image.width"
                                            :height="item.product_image.height"
                                            loading="lazy"
                                            :alt="item.product_name"
                                        />
                                    </a>
                                </template>
                                <template x-if="productIsNotVisibleInSite">
                                    <div class="w-1/4 !ml-0">
                                        <img
                                            :src="item.product_image.src"
                                            :width="item.product_image.width"
                                            :height="item.product_image.height"
                                            loading="lazy"
                                            :alt="item.product_name"
                                        />
                                    </div>
                                </template>
                                <div class="w-3/4 space-y-2">
                                    <div>
                                        <p class="text-xl">
                                            <span x-html="item.qty"></span> x <span x-html="item.product_name"></span>
                                        </p>
                                        <p class="text-sm"><span x-html="item.product_sku"></span></p>
                                    </div>
                                    <template x-for="option in item.options">
                                        <div class="pt-2">
                                            <p class="font-semibold" x-text="optionLabelText"></p>
                                            <p class="text-secondary" x-html="option.value"></p>
                                        </div>
                                    </template>
                                    <p><span x-html="item.product_price"></span></p>
                                    <div class="pt-4">
                                        <a :href="item.configure_url"
                                           x-show="productIsNotGroupedAndVisibleInSite"
                                           class="inline-flex p-2 mr-2 btn btn-primary"
                                           data-aria-label="<?= $escaper->escapeHtmlAttr(__('Edit product "%0"')) ?>"
                                           :aria-label="productAriaLabel"
                                        >
                                            <?= $heroicons->pencilHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                                        </a>
                                        <button type="button"
                                                class="inline-flex p-2 btn btn-primary"
                                                @click="deleteItemFromCart"
                                                data-aria-label="<?= $escaper->escapeHtmlAttr(__('Remove product "%0" from cart')) ?>"
                                                :aria-label="productAriaLabel"
                                        >
                                            <?= $heroicons->trashHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                                        </button>
                                    </div>

                                </div>
                            </div>
                        </template>
                    </div>
                </template>

                <template x-if="itemsCount">
                    <div>
                        <?= $block->getChildHtml('cart-drawer.totals.before'); ?>

                        <div class="relative grid gap-6 sm:gap-8 py-3 px-1 sm:px-3 bg-white">
                            <div class="w-full p-3 space-x-4 transition duration-150 ease-in-out rounded-lg hover:bg-gray-100">
                                <p><?= $escaper->escapeHtml(__('Subtotal')) ?>: <span x-html="cart.subtotal"></span></p>
                            </div>
                            <div class="w-full p-3 space-x-4 transition duration-150 ease-in-out rounded-lg hover:bg-gray-100">
                                <a @click.prevent.stop="proceedToCheckout"
                                   href="<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>"
                                   class="inline-flex btn btn-primary"
                                >
                                    <?= $escaper->escapeHtml(__('Checkout')) ?>
                                </a>
                                <span><?= $escaper->escapeHtml(__('or')) ?></span>
                                <a href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                                   class="underline"
                                >
                                    <?= $escaper->escapeHtml(__('View and Edit Cart')) ?>
                                </a>
                            </div>
                            <div x-html="getSectionDataExtraActions"></div>
                            <?= $block->getChildHtml('extra_actions'); ?>
                        </div>
                    </div>
                </template>

                <?= $block->getChildHtml('cart-drawer.bottom'); ?>
            </div>

            <button
                type="button"
                @click="closeCartDrawer"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Close minicart')) ?>"
                class="absolute top-0 right-2 p-4 mt-2 text-gray-300 transition-colors hover:text-black"
            >
                <?= $heroicons->xHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
            </button>
        </div>
        <?= $block->getChildHtml('loading') ?>
    </div>

</section>
