<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<script>
    'use strict';
    function getCookie(name) {
        var v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
        return v ? v[2] : null;
    }
    function setCookie(name, value, days) {
        var d = new Date;
        d.setTime(d.getTime() + 24*60*60*1000*days);
        document.cookie = name + "=" + value + ";path=/;expires=" + d.toGMTString();
    }
    function deleteCookie(name) { setCookie(name, '', -1); }

    window.onload = function () {
        try {
            var messages = getCookie('mage-messages');
            messages = messages ? JSON.parse(decodeURIComponent(messages).replace(/\+/g, ' ')) : [];

            window.mageMessages = messages;
        } catch (error) {
            console.warn('Error parsing Cookie Messages:', error);
            return;
        }

        var messagesEvent = new CustomEvent("messages-loaded", {
            detail: {
                messages: messages
            }
        });
        window.dispatchEvent(messagesEvent);

        deleteCookie('mage-messages');
    }
</script>
