<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<script>
    'use strict';
    function loadLorySliders(dispatch) {
        if (typeof lory !== "undefined") {
            Array.prototype.slice.call(document.querySelectorAll('.js_slider')).forEach(function (element, index) {
                function handleSlide(e) {
                    // console.log(element.querySelectorAll('.js_slide')[0].childNodes);
                }
                element.addEventListener('before.lory.slide', handleSlide);
                lory(element, {
                    rewind: true
                });
                if(dispatch) {
                    dispatch('slider-loaded', 'true' );
                }
            });
        }
    }
</script>
<script src="<?= $block->escapeUrl($block->getViewFileUrl('js/lory-2.5.3.min.js')) ?>" defer="defer"
        @load="loadLorySliders($dispatch)"
></script>
