<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<div x-data="initMenuDesktop"
     class="z-20 order-2 sm:order-1 lg:order-2 navigation hidden lg:flex"
>
    <!-- desktop -->
    <div x-ref="nav-desktop"
         @load.window="setActiveMenu"
         class="hidden lg:block lg:px-8">
        <nav
            class="relative"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
        >
            <ul class="flex justify-start flex-wrap gap-x-7 py-4">
                <?php foreach ($menuItems as $index => $menuItem): ?>
                    <li class="relative level-0 border-b-2 border-transparent hover:border-primary data-[active]:border-primary"
                        data-index="<?= $escaper->escapeHtmlAttr($index) ?>"
                        @mouseenter="enterHoverPanel"
                        @mouseleave="leaveHoverPanel"
                        @keyup.escape="leaveHoverPanel"
                    >
                        <span class="flex items-center text-md">
                            <a class="w-full text-base text-gray-700 level-0 py-2 px-0.5"
                               href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                               title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                               @focus="leaveHoverPanel"
                            >
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </a>
                            <?php if (!empty($menuItem['childData'])): ?>
                                <button
                                    type="button"
                                    data-sr-button-id="<?= $escaper->escapeHtmlAttr($index) ?>"
                                    data-index="<?= $escaper->escapeHtmlAttr($index) ?>"
                                    :aria-expanded="hoverPanelIsIndex"
                                    @click="openMenuOnClick"
                                    class="rounded p-1 text-gray-500"
                                >
                                    <?= $heroiconsSolid->chevronDownHtml("flex self-center h-5 w-5", 25, 25, ['aria-hidden' => 'true']) ?>
                                    <span class="sr-only">
                                        <?= $escaper->escapeHtml(__('Show submenu for %1 category', $menuItem['name'])) ?>
                                    </span>
                                </button>
                            <?php endif; ?>
                        </span>
                        <?php if (!empty($menuItem['childData'])): ?>
                            <ul
                                class="absolute top-full z-10 hidden px-6 py-4 mt-0.5 -ml-6 shadow-lg bg-container-lighter/95"
                                data-index="<?= $escaper->escapeHtmlAttr($index) ?>"
                                :class="childMenuClass"
                            >
                                <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                    <li>
                                        <a href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                           title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                           class="block w-full px-3 py-1 my-1 whitespace-nowrap first:mt-0 hover:underline aria-[current=page]:underline"
                                           data-index="<?= $escaper->escapeHtmlAttr($index) ?>"
                                           @keyup.escape="childMenuItemKeyUpEscape"
                                        >
                                            <span class="text-base text-gray-700">
                                                <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                            </span>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
    </div>
</div>
<script>
    'use strict';

    const initMenuDesktop = () => {
        return {
            hoverPanelActiveId: null,

            hoverPanelIsIndex() {
                return this.hoverPanelActiveId === this.$el.dataset.index
            },

            enterHoverPanel() {
                this.hoverPanelActiveId = this.$el.dataset.index
            },
            leaveHoverPanel() {
                this.hoverPanelActiveId = 0
            },

            childMenuItemKeyUpEscape() {
                this.$nextTick(() => document.querySelector('[data-sr-button-id=' + this.$el.dataset.index + ']').focus())
            },

            childMenuClass() {
                return {
                    'hidden': !this.hoverPanelIsIndex(),
                    'block': this.hoverPanelIsIndex()
                }
            },

            setActiveMenu() {
                const menuNode = this.$root

                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0]
                }).map(item => {
                    item.setAttribute('aria-current', 'page');
                    item.closest('li.level-0').setAttribute('data-active', 'true')
                })
            },
            openMenuOnClick() {
                this.hoverPanelIsIndex()
                    ? this.leaveHoverPanel()
                    : this.enterHoverPanel()
            }
        }
    }

    window.addEventListener('alpine:init', () => Alpine.data('initMenuDesktop', initMenuDesktop), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
