<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\Block\Category\View;

/** @var View $block */

/**
 * Keep the following empty line intact - it resolves a display issue if on categories without products or CMS content.
 *
 * @see https://gitlab.hyva.io/hyva-themes/magento2-default-theme/-/issues/312
 */
?>

<?php if (!$block->isContentMode() || $block->isMixedMode()): ?>
    <?= $block->getProductListHtml() ?>
<?php endif; ?>
