<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */

$label = $block->getData('label') ?? __('My Wish List');
$urlPath = $block->getData('path') ?? 'wishlist';
?>

<a
    id="<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>"
    class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100 relative"
    href="<?= $escaper->escapeUrl($block->getUrl($urlPath)) ?>"
    title="<?= $escaper->escapeHtmlAttr($label) ?>"
    x-data="wishlistItemCount"
    @private-content-loaded.window="updateItemCount"
>
    <?= $escaper->escapeHtml($label) ?>
    <template x-if="itemCount">
        <span class="tabular-nums" x-text="itemCountText"></span>
    </template>
</a>

<script>
    "use strict";
    (() => {
        const initFn = () => Alpine.data('wishlistItemCount', () => ({
            itemCount: 0,
            updateItemCount() {
                this.itemCount = parseInt(this.$event.detail.data.wishlist.counter)
            },
            itemCountText() {
                return `(${this.itemCount})`
            }
        }));
        window.Alpine ? initFn() : window.addEventListener('alpine:init', initFn, {once: true})
    })()
</script>
<?php $hyvaCsp->registerInlineScript() ?>