<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var HyvaCsp $hyvaCsp */

$label = $block->getData('label') ?? __('My Wish List');
$urlPath = $block->getData('path') ?? 'wishlist';
?>

<a
    id="<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>"
    class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100 relative"
    href="<?= $escaper->escapeUrl($block->getUrl($urlPath)) ?>"
    title="<?= $escaper->escapeHtmlAttr($label) ?>"
    x-data="wishlistItemCount"
    @private-content-loaded.window="updateItemCount"
>
    <?= $escaper->escapeHtml($label) ?>
    <template x-if="hasItems">
        <span class="tabular-nums" x-text="itemCountText"></span>
    </template>
</a>

<script>
    "use strict";
    function wishlistItemCount() {
        return {
            itemCount: 0,
            updateItemCount() {
                this.itemCount = parseInt(this.$event.detail.data.wishlist.counter)
            },
            itemCountText() {
                return `(${this.itemCount})`
            },
            hasItems()
            {
                return this.itemCount > 0;
            },
        }
    }

    window.addEventListener('alpine:init', () => Alpine.data('wishlistItemCount', wishlistItemCount), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
