<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Cart\CheckoutConfig;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */
?>

<?php
/** @var CheckoutConfig $checkoutConfigViewModel */
$checkoutConfigViewModel = $viewModels->require(CheckoutConfig::class);
$serializedCheckoutConfig =  $block->getItemsCount() ? $checkoutConfigViewModel->getSerializedCheckoutConfig() : 'false';

?>
<script>
    'use strict';

    (function( hyva, undefined ) {

        let controller = new AbortController();

        /**
         * Takes a form element and submits it through fetch,
         * then replaces the result into the document without
         * refreshing the page
         */
        hyva.postCart = (form) => {
            if (!form.action) {
                return;
            }
            controller.abort();
            controller = new AbortController();

            const action = form.action;
            const formData = new FormData(form);

            if (!formData.uenc) {
                formData.append('uenc', hyva.getUenc());
            }

            formData.append('form_key', hyva.getFormKey());

            window.fetch(action, {
                method: 'POST',
                body: formData,
                signal: controller.signal
            }).then((result) => {
                return result.text()
            }).then((content) => {

                hyva.replaceDomElement('#maincontent', content)

            }).catch((error) => {
                if (error.name !== 'AbortError') {
                    console.error(error);
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: "<?= $escaper->escapeJs(__("Something went wrong. Please try again.")) ?>"
                        }], 10000
                    );
                }
            })
        }
    }( window.hyva = window.hyva || {} ));

    function initCartMainForm() {
        return {
            cartIsEmpty: true,
            init() {
                window.checkoutConfig = JSON.parse(this.$root.dataset.checkoutConfig);
                window.customerData = window.checkoutConfig.customerData;
                window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;

                this.cartIsEmpty = !window.checkoutConfig;
            },
            checkCartShouldUpdate() {
                const cart = this.$event.detail.data.cart;

                if (cart && cart.items) {
                    if (!window.checkoutConfig) {
                        if (cart.items.length) {
                            /**
                             * We can't update only the cart contents, because scripts have to
                             * be loaded on the initial page load if CSP is enabled.
                             */
                            const isCsp = document.querySelector('script[nonce]');
                            isCsp && window.location.reload() || window.location.reload();
                        }
                        return;
                    }

                    if (window.checkoutConfig) {
                        const roundUp = (number) => Math.round(number * 100);

                        const decimalNumbersAreEqual = (number1, number2) => roundUp(number1) === roundUp(number2);

                        if (decimalNumbersAreEqual(
                            cart.items.reduce((totalQty, cartItem) => totalQty + cartItem.qty, 0),
                                window.checkoutConfig.quoteData.items_qty
                            ) &&
                            decimalNumbersAreEqual(
                                cart.subtotalAmount,
                                window.checkoutConfig.totalsData.total_segments.find((segment) => segment.code === "subtotal").value
                            )
                        ) {
                            return;
                        }
                    }
                }
                this.reloadCartContent();
            },
            reloadCartContent() {
                window.fetch(window.location.href, {
                    method: "GET"
                }).then((result) => {
                    return result.text()

                }).then((body) => {
                    hyva.setCookie('mage-cache-sessid', '', -1, true);
                    hyva.replaceDomElement('#maincontent', body)

                }).catch((error) => {
                    console.error(error);
                    window.location.reload()
                })
            },
            onStorageChange() {
                if (this.$event.key === 'private_content_version') {
                    window.dispatchEvent(new CustomEvent("reload-customer-section-data"));
                }
            },
            proceedToCheckout() {
                this.$dispatch('toggle-authentication',
                    {url: this.$el.href});
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initCartMainForm', initCartMainForm), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
<div x-data="initCartMainForm"
     class="cart-form clearfix"
     @private-content-loaded.window="checkCartShouldUpdate"
     @storage.window="onStorageChange"
     data-checkout-config="<?= $escaper->escapeHtmlAttr($serializedCheckoutConfig) ?>"
>
    <?php if ($block->getItemsCount()): ?>
        <?= $block->getChildHtml('with-items') ?>
    <?php else: ?>
        <?= $block->getChildHtml('no-items') ?>
    <?php endif; ?>
</div>
