<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Downloadable\Block\Customer\Products\ListProducts;
use Magento\Downloadable\Model\Link\Purchased\Item;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/** @var ListProducts $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<h2
    id="downloadableProducts"
    class="text-2xl mb-6"
>
    <?= $escaper->escapeHtml(__('My Downloadable Products')) ?>
</h2>
<?php $items = $block->getItems(); ?>
<?php if (count($items)): ?>
<div
    class="downloadable-products card mb-4"
    aria-labelledby="downloadableProducts"
    role="table"
>
    <div
        role="row"
        id="my-orders-table"
        class="grid grid-cols-3 lg:grid-cols-6"
    >
        <div
            role="columnheader"
            class="text-sm text-secondary p-2"
        >
            <?= $escaper->escapeHtml(__('Order #')) ?>
        </div>
        <div
            role="columnheader"
            class="text-sm lg:block text-secondary p-2"
        >
            <?= $escaper->escapeHtml(__('Date')) ?>
        </div>
        <div
            role="columnheader"
            class="text-sm lg:block text-secondary p-2"
        >
            <?= $escaper->escapeHtml(__('Title')) ?>
        </div>
        <div
            role="columnheader"
            class="text-sm lg:block text-secondary p-2 "
        >
            <?= $escaper->escapeHtml(__('Download')) ?>
        </div>
        <div
            role="columnheader"
            class="text-sm lg:block text-secondary p-2"
        >
            <?= $escaper->escapeHtml(__('Status')) ?>
        </div>
        <div
            role="columnheader"
            class="text-sm text-secondary p-2"
        >
            <?= $escaper->escapeHtml(__('Remaining Downloads')) ?>
        </div>
    </div>
    <?php $i = 0; ?>
    <?php foreach ($items as $item): ?>
        <?php $i++; ?>
        <div
            role="row"
            class="grid grid-cols-3 lg:grid-cols-6"
        >
            <div
                role="rowheader"
                class="p-2 items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                aria-label="<?= $escaper->escapeHtmlAttr($item->getPurchased()->getOrderIncrementId()) ?>"
            >
                <a
                    id="downloadableProduct<?= $escaper->escapeHtmlAttr($item->getPurchased()->getOrderId()) ?>"
                    href="<?= $escaper->escapeUrl($block->getOrderViewUrl($item->getPurchased()->getOrderId()))?>"
                    title="<?= $escaper->escapeHtml(__('View Order')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('View order') . ' ' . $item->getPurchased()->getOrderIncrementId()) ?>"
                >
                    <?= $escaper->escapeHtml($item->getPurchased()->getOrderIncrementId()) ?>
                </a>
            </div>
            <?php $date = new DateTime($item->getPurchased()->getCreatedAt()); ?>
            <div
                role="cell"
                class="p-2 items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
            >
                <!-- A11y TO DO: user should be informed about current date format, should be added in `sr-only element`. Issue: #629: https://gitlab.hyva.io/hyva-themes/magento2-default-theme/-/issues/629 -->
                <?= $escaper->escapeHtml($date->format('m/d/y')) ?>
            </div>
            <div
                role="cell"
                class="p-2 flex items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
            >
                <?= $escaper->escapeHtml($item->getPurchased()->getProductName()) ?>
            </div>
            <div
                role="cell"
                class="p-2 items-center text-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
            >
                <?php if ($item->getStatus() == Item::LINK_STATUS_AVAILABLE): ?>
                    <a
                        href="<?= $escaper->escapeUrl($block->getDownloadUrl($item)) ?>"
                        class="inline-block text-sm underline text-secondary-darker"
                        id="download_<?= /* @noEscape */ $item->getPurchased()->getProductId() ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('Start Download')) ?>"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Start Download')) ?>"
                        class="action download"
                    >
                        <?= $heroicons->documentDownloadHtml(); ?>
                    </a>
                    <?php if ($block->getIsOpenInNewWindow()): ?>
                        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                            'onclick',
                            "this.target='_blank'",
                            'a#download_' . $item->getPurchased()->getProductId()
                        ) ?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            <div
                role="cell"
                class="p-2 items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
            >
                <?= $escaper->escapeHtml(__(ucfirst($item->getStatus()))) ?>
            </div>
            <div
                role="cell"
                class="p-2 items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
            >
                <?= $escaper->escapeHtml($block->getRemainingDownloads($item)) ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<?php if ($block->getChildHtml('pager')): ?>
    <div class="toolbar downloadable-products-toolbar bottom">
        <?= $block->getChildHtml('pager') ?>
    </div>
<?php endif; ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= $escaper->escapeHtml(__('You have not purchased any downloadable products yet.')) ?></span>
    </div>
<?php endif; ?>

<div class="actions-toolbar">
    <div class="secondary">
        <a href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>" class="action back">
            <span><?= $escaper->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
