<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
?>
<script>
    function initPriceBox()
    {
        return {
            updatePrice() {
                const priceData = this.$event.detail;
                const regularPriceLabel = this.$root.querySelector('.normal-price .price-label');
                const regularPriceElement = this.$root.querySelector('.normal-price [data-price-type=finalPrice].price-wrapper .price');
                const basePriceElement = this.$root.querySelector('.normal-price [data-price-type=basePrice].price-wrapper .price');
                if (priceData.finalPrice.amount < priceData.oldPrice.amount) {
                    regularPriceLabel && regularPriceLabel.classList.add('hidden');
                } else {
                    regularPriceLabel && regularPriceLabel.classList.remove('hidden');
                }
                regularPriceElement && (regularPriceElement.innerText = hyva.formatPrice(priceData.finalPrice.amount));
                basePriceElement && (basePriceElement.innerText = hyva.formatPrice(priceData.basePrice.amount));
            },
            htmlPriceIdGroup() {
                return [this.$el.dataset.priceId];
            },
            htmlPriceId() {
                return this.$id(this.$el.closest('[data-price-id]').dataset.priceId);
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initPriceBox', initPriceBox), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
