<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPrice;
use Magento\Catalog\Block\Product\View\Options\Type\Select\Checkable;
use Magento\Catalog\Model\Product\Option;
use Magento\Catalog\Pricing\Price\CustomOptionPrice;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Checkable $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var SecureHtmlRenderer $secureRenderer */

$product = $block->getProduct();

/** @var ProductPrice $productPriceViewModel */
$productPriceViewModel = $viewModels->require(ProductPrice::class);

$option = $block->getOption();
if ($option): ?>
    <?php
    $configValue = $block->getPreconfiguredValue($option);
    if (!is_array($configValue)) {
        $configValue = (array)$configValue;
    }
    $optionType = $option->getType();
    $optionId = $option->getId();
    $require = $option->getIsRequire() ? ' required' : '';
    $arraySign = $optionType === Option::OPTION_TYPE_MULTIPLE ? '[]' : '';
    $count = 1;
    ?>

<div class="options-list nested" id="options-<?= $escaper->escapeHtmlAttr($option->getId()) ?>-list">
    <select
        name="options[<?= $escaper->escapeHtmlAttr($option->getId()) ?>]<?= /* @noEscape */ $arraySign ?>"
        id="options_<?= $escaper->escapeHtmlAttr($optionId) ?>"
        class="<?= $optionType === Option::OPTION_TYPE_MULTIPLE
                       ? 'form-multiselect'
                       : 'form-select' ?>
                       product-custom-option max-w-full"
        <?php if ($optionType === Option::OPTION_TYPE_MULTIPLE): ?>
            multiple
        <?php endif; ?>
        <?php if ($option->getIsRequire()): ?>
            required
            data-required
            @invalid="showFieldValidationMessage"
            @input="hideFieldValidationMessage"
            data-validation-message="<?= $escaper->escapeHtmlAttr(__("Please select one of the options.")) ?>"
        <?php endif; ?>
        x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>"
        data-event-target-property="currentTarget"
        @change="updateCustomOptionValue"
    >
    <?php if ($option->getType() === Option::OPTION_TYPE_DROP_DOWN): ?>
        <option value=""><?= $escaper->escapeHtml(__('-- Please Select --')) ?></option>
    <?php endif; ?>

    <?php foreach ($option->getValues() as $value): ?>
        <?php
        $checked = '';
        $count++;
        if ($arraySign) {
            $checked = is_array($configValue) && in_array($value->getOptionTypeId(), $configValue) ? 'checked' : '';
        } else {
            $checked = $configValue == $value->getOptionTypeId() ? 'checked' : '';
        }
        $dataSelector = 'options[' . $option->getId() . ']';
        if ($arraySign) {
            $dataSelector .= '[' . $value->getOptionTypeId() . ']';
        }

        $selectOptionId = $option->getId() . '_' . $value->getOptionTypeId();

        $isPercentage = $value->getPriceType() === 'percent';

        $valuePrice = $productPriceViewModel->getCustomOptionPrice($value, CustomOptionPrice::PRICE_CODE, $product);
        if ($productPriceViewModel->displayPriceInclAndExclTax()) {
            $valueBasePrice = $value->getPrice(true);
        }
        ?>

            <option type="<?= $escaper->escapeHtmlAttr($optionType) ?>"
                    value="<?= $escaper->escapeHtmlAttr($value->getOptionTypeId()) ?>"
                    <?= $escaper->escapeHtml($checked) ?>
                    x-ref="option-<?= $escaper->escapeHtmlAttr($option->getId() . '-' . $value->getOptionTypeId()) ?>"
                    data-price-amount="<?= $escaper->escapeHtmlAttr($valuePrice) ?>"
                    data-price-type="<?= $escaper->escapeHtmlAttr($value->getPriceType()) ?>"
                    data-select-option-id="<?= $escaper->escapeHtmlAttr($selectOptionId) ?>"
                <?php if (in_array($value->getOptionTypeId(), $configValue)): ?>
                   selected
                <?php endif; ?>
                data-select-option-title="<?= $escaper->escapeHtmlAttr($value->getTitle()) ?>"
                data-value-base-price="<?= $productPriceViewModel->displayPriceInclAndExclTax() ? $escaper->escapeHtmlAttr($valueBasePrice) : '' ?>"
                x-html="getSelectOptionLabel"
            >
                <?= $escaper->escapeHtml($value->getTitle()) ?>
                <?= /* @noEscape */ $block->formatPrice($value) ?>
                <?php if ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
                (<?= $escaper->escapeHtml(__('Excl. Tax')) ?>: <?= /* @noEscape */ $productPriceViewModel->format($valueBasePrice) ?>)
                <?php endif; ?>
            </option>
    <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>
