<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;

/** @var AbstractBlock $sectionBlock */
/** @var Escaper $escaper */

?>
<div class="flex pt-6 pb-3 px-6 mb-6 md:flex-row border-b-2 border-gray-300">
    <h2 class="text-gray-900 text-2xl title-font font-base text-center md:text-left w-full">
        <?= $sectionBlock->getTitle() ? $escaper->escapeHtml($sectionBlock->getTitle()) : '&nbsp;' ?>
    </h2>
</div>
