<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Customer\ReviewList;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var ReviewList $viewModelCustomerReviews */
$viewModelCustomerReviews = $viewModels->require(ReviewList::class);

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var StoreConfig $viewModelStoreConfig */
$viewModelStoreConfig = $viewModels->require(StoreConfig::class);

$productUrlSuffix = $viewModelStoreConfig->getStoreConfig('catalog/seo/product_url_suffix');
$baseUrl = $block->getBaseUrl();
$ratingSteps = 5;
?>
<div class="mb-6 text-2xl"><?= $escaper->escapeHtml(__('My Product Reviews')) ?></div>

<div id="content"
     x-data="initReviewList"
     @private-content-loaded.window="onPrivateContentLoaded">
    <template x-if="hasReviewPage">
        <div>
            <template x-if="hasMoreThanOnePage">
                <div class="flex items-center toolbar-pager">
                    <p class="flex w-4/12 text-sm leading-5 text-gray-700 toolbar-amount"
                       id="toolbar-amount"><?= $escaper->escapeHtml(__('Items')) ?>&nbsp;<span x-text="itemsPerPageFrom"
                    ></span>&nbsp;-&nbsp;<span x-text="itemsPerPageTo"></span>
                    </p>
                    <ul class="relative z-0 inline-flex w-8/12 items pages-items">
                        <li class="relative inline-flex items-center px-2 py-2 text-sm font-medium leading-5
                                text-gray-500 transition duration-150 ease-in-out bg-white border border-r-0
                                border-gray-300 item pages-item-previous rounded-l-md hover:text-gray-400
                                focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue
                                active:bg-gray-100 active:text-gray-500"
                        >
                            <a href="#" @click.prevent="goToPrevPageIfExists"
                               :class="prevPageLinkClasses"
                               title="<?= $escaper->escapeHtmlAttr(__('Previous')) ?>">
                                <span>
                                    <?= $heroicons->chevronLeftHtml('', 20, 20); ?>
                                </span>
                            </a>
                        </li>
                        <template x-for="item in Object.values(totalPagesObject)">
                            <li :class="listItemClasses"
                                class="relative inline-flex items-center text-sm font-medium leading-5 text-gray-700
                                    transition duration-150 ease-in-out bg-white border item hover:text-gray-500
                                    focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue
                                    active:bg-gray-100 active:text-gray-700">
                                <template x-if="isCurrentPage">
                                    <strong class="px-4 py-2 cursor-default page">
                                        <span x-text="item"></span>
                                    </strong>
                                </template>
                                <template x-if="isNotCurrentPage">
                                    <a class="px-4 py-2 page" href="#" @click.prevent="goToPage">
                                        <span x-text="item"></span>
                                    </a>
                                </template>
                            </li>
                        </template>
                        <li class="relative inline-flex items-center px-2 py-2 text-sm font-medium leading-5
                            text-gray-500 transition duration-150 ease-in-out bg-white border border-l-0
                            border-gray-300 item pages-item-next rounded-r-md hover:text-gray-400 focus:z-10
                            focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100
                            active:text-gray-500"
                        >
                            <a @click.prevent="goToNextPageIfExist"
                               :class="nextPageLinkClasses"
                               href="#" title="<?= $escaper->escapeHtmlAttr(__('Next')) ?>">
                                <span>
                                    <?= $heroicons->chevronRightHtml('', 20, 20); ?>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </template>
        </div>
    </template>
    <template x-if="hasReviews">
        <div>
            <template x-for="review in listReviews">
                <div class="flex my-6 card">
                    <div class="w-32">
                        <img :src="reviewProductImageUrl" :alt="reviewProductImageLabel"/></div>
                    <div class="pl-6">
                        <p class="text-lg font-medium">
                            <a :href="reviewProductUrl" x-text="reviewProductName"></a>
                        </p>
                        <p class="mb-2 text-sm">
                            <?= $escaper->escapeHtml(__('Created at')) ?>
                            <span x-text="reviewDate"></span>
                        </p>
                        <template x-for="(item, index) in review.ratings_breakdown" :key="index">
                            <div class="flex">
                                <template x-for="ratingStep in getRatingSteps">
                                    <div>
                                        <template x-if="hasRatingStep">
                                            <?= $heroiconsSolid->starHtml('text-yellow-400'); ?>
                                        </template>
                                        <template x-if="hasNotRatingStep">
                                            <?= $heroiconsSolid->starHtml('text-gray-400'); ?>
                                        </template>
                                    </div>
                                </template>
                            </div>
                        </template>
                        <div class="mt-1 leading-relaxed">
                            <p class="font-semibold" x-text="review.summary"></p>
                            <p x-text="review.text"></p>
                        </div>
                    </div>
                </div>
            </template>
        </div>
    </template>
    <?= $block->getChildHtml('loading') ?>
    <template x-if="hasNoReviews">
        <p><?= $escaper->escapeHtml(__('You have submitted no reviews.')) ?></p>
    </template>
</div>
<script>
    function initReviewList() {
        return {
            customerToken: false,
            onPrivateContentLoaded() {
                const data = this.$event.detail.data;
                this.customerToken = data.customer['signin_token'];
                if (this.customerToken) {
                    this.getReviewsList();
                } else {
                   this.isLoading = false;
                }
            },
            currentPage: 1,
            pageSize: 5,
            totalPagesObject: {},
            pageInfo: {},
            isLoading: true,
            reviews: {},
            hasReviewPage() {
                return this.pageInfo && this.pageInfo.page_size && this.pageInfo.total_pages;
            },
            hasReviews() {
                return this.reviews && this.reviews.length;
            },
            itemsPerPageFrom() {
                return this.currentPage > 1 && (this.currentPage - 1) * this.pageSize + 1 || 1;
            },
            itemsPerPageTo() {
                return this.currentPage > 1 && (this.currentPage) * this.pageSize || this.pageSize;
            },
            hasMoreThanOnePage() {
                return this.pageInfo.total_pages > 1;
            },
            prevPageLinkClasses() {
                return {
                    'cursor-default': this.currentPage < 2,
                }
            },
            nextPageLinkClasses() {
                return {
                    'cursor-default': this.currentPage >= this.pageInfo.total_pages,
                }
            },
            listItemClasses() {
                return {
                    'border-primary -ml-px': this.item === this.pageInfo.current_page,
                    'border-gray-300' : this.item !== this.pageInfo.current_page,
                }
            },
            isCurrentPage() {
                return this.item === this.pageInfo.current_page;
            },
            isNotCurrentPage() {
                return ! this.isCurrentPage();
            },
            goToPrevPageIfExists() {
                this.currentPage > 1 && this.setCurrentPage(this.currentPage - 1);
            },
            goToNextPageIfExists() {
                this.currentPage < this.pageInfo.total_pages && this.setCurrentPage(this.currentPage + 1);
            },
            setCurrentPage(page) {
                this.currentPage = page;
                this.getReviewsList();
            },
            goToPage() {
                this.setCurrentPage(this.item);
            },
            reviewProductImageUrl() {
                return this.review.product && this.review.product.image && this.review.product.image.url;
            },
            reviewProductImageLabel() {
                return this.review.product && this.review.product.image && this.review.product.image.label;
            },
            reviewProductUrl() {
                return this.review.product && this.review.product.url_key && (
                                '<?= $escaper->escapeJs($baseUrl) ?>' +
                                 this.review.product.url_key  +
                                 '<?= $escaper->escapeJs($productUrlSuffix) ?>'
                               );
            },
            reviewProductName() {
                return this.review.product && this.review.product.name;
            },
            reviewDate() {
                return this.review && this.review.created_at && new Date(this.review.created_at).toLocaleDateString();
            },
            getCustomerReviewsQuery() {
                return <?= /** @noEscape */ json_encode(
                    '{customer {' . $viewModelCustomerReviews->getCustomerReviewsGraphQlQuery() . '}}'
                ); ?>.replace('%currentPage%', this.currentPage).replace('%pageSize%', this.pageSize)
            },
            getRatingSteps() {
                return <?= /** @noEscape */ json_encode(range(1, $ratingSteps)) ?>;
            },
            hasRatingStep() {
                return this.ratingStep <= this.item.value;
            },
            hasNotRatingStep() {
                return this.ratingStep > this.item.value;
            },
            hasNoReviews() {
                return !this.isLoading && !(this.reviews && this.reviews.length);
            },
            listReviews() {
                return Object.values(this.reviews);
            },
            getReviewsList() {
                this.isLoading = true;
                return fetch(`${BASE_URL}graphql`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'Store': '<?= $escaper->escapeHtmlAttr($viewModelStore->getStoreCode()) ?>'
                        },
                        credentials: 'include',
                        body: JSON.stringify({
                            query: this.getCustomerReviewsQuery()
                        })
                    }
                ).then(
                    (response) => response.json()
                ).then((data) => {
                    if (data && data.errors) {
                        this.initErrorMessages(data.errors);
                    } else {
                        this.reviews = (
                            data &&
                            data.data &&
                            data.data.customer &&
                            data.data.customer.reviews &&
                            data.data.customer.reviews.items || []
                        );
                        this.pageInfo = (
                            data &&
                            data.data &&
                            data.data.customer &&
                            data.data.customer.reviews &&
                            data.data.customer.reviews.page_info || []
                        );
                        this.totalPagesObject = (
                            this.pageInfo &&
                            this.pageInfo.total_pages &&
                            Array.from(
                                { length: this.pageInfo.total_pages },
                                (v, i) => i + 1
                            ) || []
                        );
                    }
                    this.isLoading = false;
                });
            },
            initErrorMessages(errors) {
                const messages = [];
                for (const error in Object.keys(errors)) {
                    messages.push({type: 'error', text: errors[error].message});
                }
                dispatchMessages(messages)
            },
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initReviewList', initReviewList), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
