<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\ProductAttributes as ProductAttributes;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

/** @var Product $product */
if (! ($product = $block->getData('product'))) {
    return;
}

$productId = $product->getId();

$productAttribute = $viewModels->require(ProductAttributes::class);
$productName = $productAttribute->getValue($product, 'name');

?>

<button x-data="initWishlist()"
        x-defer="intersect"
        @click.prevent="addToWishlist(<?= (int) $productId ?>)"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List') . ' ' . $productName) ?>"
        type="button"
        class="btn p-2 rounded-full hover:text-red-600"
        data-addto="wishlist"
>
    <?= $lucideIcons->heartHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
</button>
