<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
    <button type="button"
            data-role="all-tocart"
            title="<?= $escaper->escapeHtmlAttr(__('Add All to Cart')) ?>"
            class="action tocart">
        <span><?= $escaper->escapeHtml(__('Add All to Cart')) ?></span>
    </button>
<?php endif;?>
