<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Swatches\Block\LayeredNavigation\RenderLayered;
use Magento\Swatches\Model\Swatch;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var RenderLayered $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

/** @var ConfigurableViewModel $configurableViewModel */
$configurableViewModel = $viewModels->require(ConfigurableViewModel::class);

$swatchData = $block->getSwatchData();
?>
<div class="swatch-attribute swatch-layered <?= $escaper->escapeHtmlAttr($swatchData['attribute_code']) ?>"
     x-data="initLayeredSwatch"
>
    <div class="swatch-attribute-options clearfix">
        <?php foreach ($swatchData['options'] as $option => $label): ?>
            <?php
            // check required if attribute property "is_filterable" is set to "Filterable (no results)"
            if (!isset($swatchData['swatches'][$option])) {
                continue;
            }

            $swatchType = (string) $swatchData['swatches'][$option]['type'];
            $swatchValue = (string) $swatchData['swatches'][$option]['value'];
            $isVisualSwatch = in_array((int) $swatchType, [Swatch::SWATCH_TYPE_VISUAL_COLOR, Swatch::SWATCH_TYPE_VISUAL_IMAGE], true);
            ?>
            <a
                href="<?= $escaper->escapeUrl($label['link']) ?>" rel="nofollow"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Filter %1 %2', $swatchData['attribute_label'], $label['label'])) ?>"
                class="swatch-option-link-layered swatch-option cursor-pointer bg-container-lighter shadow-sm relative select-none border-container-darker <?= $isVisualSwatch ? 'w-6 h-6' : '' ?>"
                <?php if ($isVisualSwatch): ?>
                    style="<?= $swatchType === '2'
                        ? 'background: #fff url(' . $escaper->escapeUrl($block->getSwatchPath('swatch_image', $swatchValue)) . ') center no-repeat'
                        : 'background-color: ' . (/* @noEscape */ $swatchType === '1' ? $swatchValue : '') ?>;"
                <?php endif; ?>
                <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
                    <?php if ((int) $swatchType !== Swatch::SWATCH_TYPE_TEXTUAL): ?>
                        <?php $swatchThumbPath = $swatchType === "2" ? $block->getSwatchPath('swatch_thumb', $swatchValue) : ''; ?>
                    <?php endif; ?>
                    data-swatch-label="<?= $escaper->escapeHtmlAttr($label['label']) ?>"
                    data-swatch-thumb="<?= $escaper->escapeHtmlAttr($swatchThumbPath ?? '') ?>"
                    @mouseenter.self="onMouseEnter"
                    @mouseleave.self="onMouseLeave"
                <?php endif; ?>
            >
                <?php if ($swatchType === "0"): ?>
                    <?= $escaper->escapeHtml($swatchValue ?: $label['label']) ?>
                <?php endif; ?>
            </a>
        <?php endforeach; ?>
    </div>
    <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
        <?= /* @noEscape */ $block->getBlockHtml('product.swatch.tooltip'); ?>
    <?php endif; ?>
</div>

