<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Hyva\Theme\ViewModel\ProductAlert;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var ProductAlert $productAlertViewModel */
$productAlertViewModel = $viewModels->require(ProductAlert::class);
/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);
/** @var Product $product */
$product = $currentProduct->get();

if (!$currentProduct->exists() || !$productAlertViewModel->showPriceAlert($product)) {
    return;
}

$signupLabel = __("Notify me when the price drops");
?>
<div class="product alert price text-right">
    <a href="<?= $escaper->escapeUrl($productAlertViewModel->getSaveUrl($product, 'price')) ?>"
       title="<?= $escaper->escapeHtml($signupLabel) ?>" class="action alert">
        <span class="text-orange-400">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                 viewBox="0 0 24 24" stroke="currentColor"
                 class="w-6 h-6 inline"
            >
                <path stroke-linecap="round"
                      stroke-linejoin="round" stroke-width="2"
                      d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0
                      00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214
                      1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
            </svg>
        </span>
        <span class="underline">
            <?= $escaper->escapeHtml($signupLabel) ?>
        </span>
    </a>
</div>
