<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\BlockCache;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\Block\Product\ListProduct;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;

/** @var ListProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$blockCacheViewModel = $viewModels->require(BlockCache::class);
$productViewModel    = $viewModels->require(ProductPage::class);

?>
<?php if ($block->getProductCollection() && $block->getProductCollection()->getSize()): ?>
    <?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $templateType = ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $escaper->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <div class="mx-auto grid gap-4 <?= $mode === 'grid' ? 'sm:grid-cols-2 lg:grid-cols-4' : 'grid-cols-1' ?>">
                <?php /** @var Product $item */ ?>
                <?php foreach ($items as $item):
                    $itemCacheKeyInfo = [
                        $item->getId(),
                        $mode,
                        $templateType,
                        $block->getTemplate(),
                        $item->getStoreId(),
                        $productViewModel->getCurrencyData()['code'],
                        0, // hide details,
                        0, // hide rating summary,
                        '0' // category Id
                    ]; ?>
                    <?= $block->getLayout()->getBlock('product_list_item')
                              ->setData('product', $item)
                              ->setData('view_mode', $mode)
                              ->setData('image_display_area', $image)
                              ->setData('show_description', $description)
                              ->setData('template_type', $templateType)
                              ->setData('cache_lifetime', 3600)
                              ->setData('cache_tags', $item->getIdentities())
                              ->setData('cache_key', $blockCacheViewModel->hashCacheKeyInfo($itemCacheKeyInfo))
                              ->toHtml() ?>
                <?php endforeach ?>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif ?>
