<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Customer\Block\Account\AuthorizationLink;

/** @var Escaper $escaper */
/** @var AuthorizationLink $block */
/** @var HyvaCsp $hyvaCsp */
?>
<?php if ($block->isLoggedIn()): ?>
    <?php $dataPostParam = $block->getPostParams(); ?>
    <li class="nav item">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
            @click.prevent='hyva.postForm(<?= /* @noEscape */ $dataPostParam ?>)'
        >
            <?= $escaper->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php else: ?>
    <li class="nav item">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
            <?= $escaper->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php endif; ?>
