<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<template x-if="cartData.items && cartData.items.length">
    <div class="coupon-form pt-6">
        <div class="mx-auto md:mx-0">
            <div class="text-left">
                <span @click="showCouponForm = !showCouponForm"
                      class="cursor-pointer text-primary-lighter select-none whitespace-nowrap"
                      id="discount-form-toggle"
                >
                    <span class="underline">
                        <?= $escaper->escapeHtml(__('Apply Discount')) ?>
                    </span>
                    <span class="inline-block ml-2">
                        <?= $heroicons->chevronUpHtml('', 16, 16, ['x-show' => 'showCouponForm']); ?>
                        <?= $heroicons->chevronDownHtml('', 16, 16, ['x-show' => '!showCouponForm']); ?>
                    </span>
                </span>
            </div>
            <div>
                <form id="discount-coupon-form"
                      class="block my-4 card"
                      x-show="showCouponForm"
                      x-on:submit.prevent="dispatchCouponMutationRequest();"
                      action=""
                      method="post"
                >
                    <div class="fieldset coupon">
                        <input type="hidden" name="remove" id="remove-coupon" value="0"/>
                        <div class="flex flex-col sm:flex-row gap-2 justify-center md:justify-start">
                            <input type="text"
                                   class="form-input text-center md:text-left border-background-dark"
                                   id="coupon_code"
                                   name="coupon_code"
                                   value=""
                                   :placeholder="cartData.applied_coupons ?
                                    cartData.applied_coupons[0]['code'] :
                                    '<?= $escaper->escapeHtmlAttr(__('Enter discount code')) ?>'"
                                   :disabled="cartData.applied_coupons"
                            />
                                <button class="btn btn-primary md:text-sm lg:text-base justify-center" type="submit"
                                        value="<?= $escaper->escapeHtmlAttr(__('Apply Coupon Code')) ?>">
                                    <span x-show="!cartData.applied_coupons">
                                        <?= $escaper->escapeHtml(__('Apply Discount')) ?>
                                    </span>
                                    <span x-show="cartData.applied_coupons">
                                        <?= $escaper->escapeHtml(__('Cancel Coupon')) ?>
                                    </span>
                                </button>
                        </div>
                    </div>
                    <?php /**
                           * @todo: revive captcha integration?
                        $block->getChildHtml('captcha')
                           */ ?>
                </form>
            </div>
        </div>
    </div>
</template>
