<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
?>
<div class="lg:w-1/4 md:w-1/2 w-full px-4">
    <form class="form subscribe"
          action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
          method="post"
          id="newsletter-validate-detail">
        <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3 uppercase">
            <?= $block->escapeHtml(__('Newsletter')) ?>
        </h2>
        <div class="flex xl:flex-no-wrap md:flex-no-wrap lg:flex-wrap flex-wrap justify-center md:justify-start">
            <input name="email" type="email" required id="newsletter" class="input input-light"
                   placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>" type="text"
            />
            <?= $block->getBlockHtml('formkey') ?>
            <button class="lg:mt-2 xl:mt-0 flex-shrink-0 inline-flex btn btn-primary">
                <?= $block->escapeHtmlAttr(__('Subscribe')) ?>
            </button>
        </div>
    </form>
</div>
