<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Modal;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */
$modalViewModel = $viewModels->require(Modal::class);
$storeViewModel = $viewModels->require(Store::class);
$order = $block->getData('order');

$modal = $modalViewModel->createModal()->withContent(<<<END_OF_CONTENT
<div
    id="cancel-order-modal-title"
    class="text-xl mb-2" 
    x-text="cancelOrderModalTitle"
></div>
<div class="field field-reserved required">
    <label for="cancel-order-reason">
        <span>{$block->escapeHtml(__('Provide a cancellation reason:'))}</span>
    </label>
    <select id="cancel-order-reason" class="form-select max-w-full" x-ref="reason" required>
        <option value=""></option>
        <template x-for="reason in reasons">
            <option :value="reason" x-text="reason"></option>
        </template>
    </select>
</div>
<div class="mt-4 flex justify-between gap-2">
    <button @click="clickedConfirm" type="button" class="btn btn-primary order-2">
        {$escaper->escapeHtml(__('Confirm'))}
    </button>
    <button @click="cancel" type="button" class="btn order-1">
        {$escaper->escapeHtml(__('Close'))}
    </button>
</div>
END_OF_CONTENT
)
->withAriaLabelledby('cancel-order-modal-title')
->addDialogClass('m-4');

?>
<script>
    (() => {
        function initOrderCancellationModal() {
            return Object.assign(
                hyva.modal.apply(this),
                hyva.formValidation.call(this, this.$el),
                {
                    order_id: null,
                    increment_id: null,
                    reasons: [],
                    setOrder(event) {
                        this.order_id = event.detail.order_id;
                        this.increment_id = event.detail.increment_id;
                        this.reasons = event.detail.reasons;
                    },
                    cancelOrder(order_id, reason) {
                        const restBaseUrl = BASE_URL + 'rest/' + CURRENT_STORE_CODE;
                        fetch(`${restBaseUrl}/V1/customers/me/cancel-order/${order_id}`, {
                            method: 'PUT',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-Requested-With': 'XMLHttpRequest'
                            },
                            body: JSON.stringify({'reason': reason}),
                        })
                            .then(response => response.json())
                            .then(result => {
                                if (result.message && result.message.length) {
                                    return dispatchMessages([{text: result.message, type: 'error'}]);
                                }
                                if (result.status === 'canceled') {
                                    hyva.setCookie('mage-messages', JSON.stringify([{
                                        text: hyva.str('<?= $escaper->escapeJs(__('Order %1 canceled.')) ?>', result.increment_id),
                                        type: 'success'
                                    }]), 1, true);
                                }
                                window.location.reload();
                            })
                    },
                    confirmCancelOrder() {
                        this.setOrder(this.$event);
                        <?= /** @noEscape */ $modal->getShowJs() ?>.then(result => result && this.cancelOrder(this.order_id, this.$refs.reason.value));
                    },
                    cancelOrderModalTitle() {
                        return `<?= $escaper->escapeJs(__('Cancel order')) ?> ${this.increment_id}`
                    },
                    clickedConfirm() {
                        return this.validateSafe().then(result => result && this.ok())
                    }
                }
            )
        }

        const initFn = () => Alpine.data('initOrderCancellationModal', initOrderCancellationModal);
        window.Alpine ? initFn() : window.addEventListener('alpine:init', initFn, {once: true})
    })()
</script>
<?php $hyvaCsp->registerInlineScript() ?>
<form
    x-data="initOrderCancellationModal"
    @submit.prevent
    @confirm-cancel-order.window="confirmCancelOrder"
    x-show="order_id"
>
    <?= /** @noEscape */ $modal ?>
</form>
