<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

?>
<script>
    function initSwatchOptions(swatchConfig) {
        return {
            swatchConfig,
            getAttributeSwatchData(attributeId) {
                const swatchConfig = Object.assign({}, this.swatchConfig[attributeId]);
                swatchConfig['details'] = JSON.parse(swatchConfig['additional_data']);

                return swatchConfig;
            },
            getAllAttributeOptions(attributeId) {
                return (
                    this.optionConfig.attributes[attributeId] &&
                    this.optionConfig.attributes[attributeId].options
                ) || []
            },
            optionIsActive(attributeId, optionId) {
                return !!this.getAllowedAttributeOptions(attributeId).find(
                    option => option.id === optionId
                )
            },
            getVisualSwatchType(attributeId) {
                // All options for an attribute have the same type, use the first one
                for (const optionId in this.swatchConfig[attributeId]) {
                    const option = this.swatchConfig[attributeId][optionId];
                    if (option.type) {
                        switch (option.type) {
                            case "1":
                                return "color"
                            case "2":
                                return "image"
                            case "3":
                                return "empty"
                            case "0":
                            default:
                                return "text"
                        }
                    }
                }
            },
            getSwatchType(attributeId, itemId) {
                // Deserialize the attribute details the first time they are used
                if (this.swatchConfig[attributeId] && ! this.swatchConfig[attributeId].details) {
                    this.swatchConfig[attributeId] = this.getAttributeSwatchData(attributeId);
                }
                const type =  this.swatchConfig[attributeId] &&
                    this.swatchConfig[attributeId].details &&
                    this.swatchConfig[attributeId].details.swatch_input_type ||
                    "empty";
                return type === 'visual' ? this.getVisualSwatchType(attributeId) : type;
            },
            isTextSwatch(attributeId, itemId) {
                return this.getSwatchType(attributeId, itemId) === 'text';
            },
            isVisualSwatch(attributeId, itemId) {
                const type = this.getSwatchType(attributeId, itemId);

                return ['image', 'color'].includes(type);
            },
            getSwatchBackgroundStyle(attributeId, itemId) {
                const config = this.getSwatchConfig(attributeId, itemId);
                const type = this.getSwatchType(attributeId);
                if (type === "color") {
                        return 'background-color:' + config.value;
                } else if (type === "image") {
                        return "background: #ffffff url('" + config.value + "') no-repeat center";
                } else {
                    return '';
                }
            },
            getSwatchText(attributeId, itemId){
                const config = this.getSwatchConfig(attributeId, itemId);
                return config.label || config.value || this.getOptionLabelFromOptionConfig(attributeId, itemId);
            },
            getOptionLabelFromOptionConfig(attributeId, itemId) {
                // Fallback if no value is present in swatchConfig data
                // Reference issue https://gitlab.hyva.io/hyva-themes/magento2-default-theme/-/issues/190
                const option = this.getAllAttributeOptions(attributeId).filter(option => option.id === itemId);
                return option && option[0] && option[0].label ||'';
            },
            getSwatchConfig(attributeId, itemId) {
                return this.swatchConfig[attributeId] && this.swatchConfig[attributeId][itemId]
                    ? this.swatchConfig[attributeId][itemId]
                    : false;
            },
            activeTooltipItem: false,
            tooltipPositionElement: false,
            isTooltipVisible() {
                return this.activeTooltipItem &&
                    this.getSwatchConfig(
                        this.activeTooltipItem.attribute,
                        this.activeTooltipItem.item
                    );
            },
            getTooltipImageStyle(attributeId, itemId) {
                const config = this.getSwatchConfig(attributeId, itemId);
                const type = this.getSwatchType(attributeId);

                if (type === "color") {
                    return 'background-color:' + config.value + '; width: 110px; height: 90px;';
                } else if (type === "image") {
                    return "background: #ffffff url('" + config.thumb +
                        "') center center no-repeat; width: 110px; height: 90px;";
                } else {
                    return 'display:none';
                }
            },
            getTooltipPosition() {
                return this.tooltipPositionElement ?
                    `top: ${this.tooltipPositionElement.offsetTop}px;` +
                    `left: ${
                        this.tooltipPositionElement.offsetLeft - (
                            this.tooltipPositionElement.closest('.snap') &&
                            this.tooltipPositionElement.closest('.snap').scrollLeft ||
                            0
                        )
                    }px;` : ''
            },
            getTooltipLabel() {
                return this.getSwatchConfig(this.activeTooltipItem.attribute, this.activeTooltipItem.item).label
            },
            focusedLabel: false,
            focusLabel(optionId) {
                this.focusedLabel = optionId;
            },
            blurLabel() {
                this.focusedLabel = false;
            }
        }
    }
</script>
