<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Tax\Pricing\Render\Adjustment;

/** @var Adjustment $block */
/** @var Escaper $escaper */

?>
<?php if ($block->displayBothPrices()): ?>
    <span id="<?= $escaper->escapeHtmlAttr($block->buildIdWithPrefix('price-excluding-tax-')) ?>"
          data-label="<?= $escaper->escapeHtmlAttr(__('Excl. Tax')) ?>"
          data-price-amount="<?= /* @noEscape */ $block->getRawAmount() ?>"
          class="price-wrapper price-excluding-tax">
        <span class="price"><?= /* @noEscape */ $block->getDisplayAmountExclTax() ?></span>
    </span>
<?php endif; ?>
